// Code generated by ent, DO NOT EDIT.

package accountsharemembership

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/your-org/ai-gateway-platform/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// RoomID applies equality check predicate on the "room_id" field. It's identical to RoomIDEQ.
func RoomID(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldRoomID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldAccountID, v))
}

// ConsumerUserID applies equality check predicate on the "consumer_user_id" field. It's identical to ConsumerUserIDEQ.
func ConsumerUserID(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldConsumerUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldAPIKeyID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldStatus, v))
}

// JoinedAt applies equality check predicate on the "joined_at" field. It's identical to JoinedAtEQ.
func JoinedAt(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldJoinedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldEndedAt, v))
}

// QueueExpiresAt applies equality check predicate on the "queue_expires_at" field. It's identical to QueueExpiresAtEQ.
func QueueExpiresAt(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldQueueExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLTE(FieldUpdatedAt, v))
}

// RoomIDEQ applies the EQ predicate on the "room_id" field.
func RoomIDEQ(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldRoomID, v))
}

// RoomIDNEQ applies the NEQ predicate on the "room_id" field.
func RoomIDNEQ(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNEQ(FieldRoomID, v))
}

// RoomIDIn applies the In predicate on the "room_id" field.
func RoomIDIn(vs ...int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIn(FieldRoomID, vs...))
}

// RoomIDNotIn applies the NotIn predicate on the "room_id" field.
func RoomIDNotIn(vs ...int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotIn(FieldRoomID, vs...))
}

// RoomIDGT applies the GT predicate on the "room_id" field.
func RoomIDGT(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGT(FieldRoomID, v))
}

// RoomIDGTE applies the GTE predicate on the "room_id" field.
func RoomIDGTE(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGTE(FieldRoomID, v))
}

// RoomIDLT applies the LT predicate on the "room_id" field.
func RoomIDLT(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLT(FieldRoomID, v))
}

// RoomIDLTE applies the LTE predicate on the "room_id" field.
func RoomIDLTE(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLTE(FieldRoomID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLTE(FieldAccountID, v))
}

// ConsumerUserIDEQ applies the EQ predicate on the "consumer_user_id" field.
func ConsumerUserIDEQ(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldConsumerUserID, v))
}

// ConsumerUserIDNEQ applies the NEQ predicate on the "consumer_user_id" field.
func ConsumerUserIDNEQ(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNEQ(FieldConsumerUserID, v))
}

// ConsumerUserIDIn applies the In predicate on the "consumer_user_id" field.
func ConsumerUserIDIn(vs ...int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIn(FieldConsumerUserID, vs...))
}

// ConsumerUserIDNotIn applies the NotIn predicate on the "consumer_user_id" field.
func ConsumerUserIDNotIn(vs ...int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotIn(FieldConsumerUserID, vs...))
}

// ConsumerUserIDGT applies the GT predicate on the "consumer_user_id" field.
func ConsumerUserIDGT(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGT(FieldConsumerUserID, v))
}

// ConsumerUserIDGTE applies the GTE predicate on the "consumer_user_id" field.
func ConsumerUserIDGTE(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGTE(FieldConsumerUserID, v))
}

// ConsumerUserIDLT applies the LT predicate on the "consumer_user_id" field.
func ConsumerUserIDLT(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLT(FieldConsumerUserID, v))
}

// ConsumerUserIDLTE applies the LTE predicate on the "consumer_user_id" field.
func ConsumerUserIDLTE(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLTE(FieldConsumerUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotNull(FieldAPIKeyID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldContainsFold(FieldStatus, v))
}

// JoinedAtEQ applies the EQ predicate on the "joined_at" field.
func JoinedAtEQ(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldJoinedAt, v))
}

// JoinedAtNEQ applies the NEQ predicate on the "joined_at" field.
func JoinedAtNEQ(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNEQ(FieldJoinedAt, v))
}

// JoinedAtIn applies the In predicate on the "joined_at" field.
func JoinedAtIn(vs ...time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIn(FieldJoinedAt, vs...))
}

// JoinedAtNotIn applies the NotIn predicate on the "joined_at" field.
func JoinedAtNotIn(vs ...time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotIn(FieldJoinedAt, vs...))
}

// JoinedAtGT applies the GT predicate on the "joined_at" field.
func JoinedAtGT(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGT(FieldJoinedAt, v))
}

// JoinedAtGTE applies the GTE predicate on the "joined_at" field.
func JoinedAtGTE(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGTE(FieldJoinedAt, v))
}

// JoinedAtLT applies the LT predicate on the "joined_at" field.
func JoinedAtLT(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLT(FieldJoinedAt, v))
}

// JoinedAtLTE applies the LTE predicate on the "joined_at" field.
func JoinedAtLTE(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLTE(FieldJoinedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotNull(FieldEndedAt))
}

// QueueExpiresAtEQ applies the EQ predicate on the "queue_expires_at" field.
func QueueExpiresAtEQ(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldEQ(FieldQueueExpiresAt, v))
}

// QueueExpiresAtNEQ applies the NEQ predicate on the "queue_expires_at" field.
func QueueExpiresAtNEQ(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNEQ(FieldQueueExpiresAt, v))
}

// QueueExpiresAtIn applies the In predicate on the "queue_expires_at" field.
func QueueExpiresAtIn(vs ...time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIn(FieldQueueExpiresAt, vs...))
}

// QueueExpiresAtNotIn applies the NotIn predicate on the "queue_expires_at" field.
func QueueExpiresAtNotIn(vs ...time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotIn(FieldQueueExpiresAt, vs...))
}

// QueueExpiresAtGT applies the GT predicate on the "queue_expires_at" field.
func QueueExpiresAtGT(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGT(FieldQueueExpiresAt, v))
}

// QueueExpiresAtGTE applies the GTE predicate on the "queue_expires_at" field.
func QueueExpiresAtGTE(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldGTE(FieldQueueExpiresAt, v))
}

// QueueExpiresAtLT applies the LT predicate on the "queue_expires_at" field.
func QueueExpiresAtLT(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLT(FieldQueueExpiresAt, v))
}

// QueueExpiresAtLTE applies the LTE predicate on the "queue_expires_at" field.
func QueueExpiresAtLTE(v time.Time) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldLTE(FieldQueueExpiresAt, v))
}

// QueueExpiresAtIsNil applies the IsNil predicate on the "queue_expires_at" field.
func QueueExpiresAtIsNil() predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldIsNull(FieldQueueExpiresAt))
}

// QueueExpiresAtNotNil applies the NotNil predicate on the "queue_expires_at" field.
func QueueExpiresAtNotNil() predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.FieldNotNull(FieldQueueExpiresAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountShareMembership) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountShareMembership) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountShareMembership) predicate.AccountShareMembership {
	return predicate.AccountShareMembership(sql.NotPredicates(p))
}
