// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/your-org/ai-gateway-platform/ent/accountshareroom"
)

// AccountShareRoom is the model entity for the AccountShareRoom schema.
type AccountShareRoom struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SeatLimit holds the value of the "seat_limit" field.
	SeatLimit int `json:"seat_limit,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// AllowedModels holds the value of the "allowed_models" field.
	AllowedModels []string `json:"allowed_models,omitempty"`
	// PerUserConcurrency holds the value of the "per_user_concurrency" field.
	PerUserConcurrency int `json:"per_user_concurrency,omitempty"`
	// QueueMax holds the value of the "queue_max" field.
	QueueMax int `json:"queue_max,omitempty"`
	// Version holds the value of the "version" field.
	Version      int `json:"version,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountShareRoom) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountshareroom.FieldAllowedModels:
			values[i] = new([]byte)
		case accountshareroom.FieldRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case accountshareroom.FieldID, accountshareroom.FieldAccountID, accountshareroom.FieldOwnerUserID, accountshareroom.FieldSeatLimit, accountshareroom.FieldPerUserConcurrency, accountshareroom.FieldQueueMax, accountshareroom.FieldVersion:
			values[i] = new(sql.NullInt64)
		case accountshareroom.FieldName, accountshareroom.FieldStatus:
			values[i] = new(sql.NullString)
		case accountshareroom.FieldCreatedAt, accountshareroom.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountShareRoom fields.
func (_m *AccountShareRoom) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountshareroom.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountshareroom.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountshareroom.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountshareroom.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountshareroom.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case accountshareroom.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case accountshareroom.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case accountshareroom.FieldSeatLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seat_limit", values[i])
			} else if value.Valid {
				_m.SeatLimit = int(value.Int64)
			}
		case accountshareroom.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case accountshareroom.FieldAllowedModels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_models", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedModels); err != nil {
					return fmt.Errorf("unmarshal field allowed_models: %w", err)
				}
			}
		case accountshareroom.FieldPerUserConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field per_user_concurrency", values[i])
			} else if value.Valid {
				_m.PerUserConcurrency = int(value.Int64)
			}
		case accountshareroom.FieldQueueMax:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field queue_max", values[i])
			} else if value.Valid {
				_m.QueueMax = int(value.Int64)
			}
		case accountshareroom.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountShareRoom.
// This includes values selected through modifiers, order, etc.
func (_m *AccountShareRoom) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountShareRoom.
// Note that you need to call AccountShareRoom.Unwrap() before calling this method if this AccountShareRoom
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountShareRoom) Update() *AccountShareRoomUpdateOne {
	return NewAccountShareRoomClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountShareRoom entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountShareRoom) Unwrap() *AccountShareRoom {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountShareRoom is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountShareRoom) String() string {
	var builder strings.Builder
	builder.WriteString("AccountShareRoom(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("seat_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.SeatLimit))
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("allowed_models=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedModels))
	builder.WriteString(", ")
	builder.WriteString("per_user_concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.PerUserConcurrency))
	builder.WriteString(", ")
	builder.WriteString("queue_max=")
	builder.WriteString(fmt.Sprintf("%v", _m.QueueMax))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// AccountShareRooms is a parsable slice of AccountShareRoom.
type AccountShareRooms []*AccountShareRoom
