// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/your-org/ai-gateway-platform/ent/accountsharemembership"
	"github.com/your-org/ai-gateway-platform/ent/predicate"
)

// AccountShareMembershipDelete is the builder for deleting a AccountShareMembership entity.
type AccountShareMembershipDelete struct {
	config
	hooks    []Hook
	mutation *AccountShareMembershipMutation
}

// Where appends a list predicates to the AccountShareMembershipDelete builder.
func (_d *AccountShareMembershipDelete) Where(ps ...predicate.AccountShareMembership) *AccountShareMembershipDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountShareMembershipDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountShareMembershipDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountShareMembershipDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountsharemembership.Table, sqlgraph.NewFieldSpec(accountsharemembership.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountShareMembershipDeleteOne is the builder for deleting a single AccountShareMembership entity.
type AccountShareMembershipDeleteOne struct {
	_d *AccountShareMembershipDelete
}

// Where appends a list predicates to the AccountShareMembershipDelete builder.
func (_d *AccountShareMembershipDeleteOne) Where(ps ...predicate.AccountShareMembership) *AccountShareMembershipDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountShareMembershipDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountsharemembership.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountShareMembershipDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
