// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/your-org/ai-gateway-platform/ent/accountshareroom"
	"github.com/your-org/ai-gateway-platform/ent/predicate"
)

// AccountShareRoomDelete is the builder for deleting a AccountShareRoom entity.
type AccountShareRoomDelete struct {
	config
	hooks    []Hook
	mutation *AccountShareRoomMutation
}

// Where appends a list predicates to the AccountShareRoomDelete builder.
func (_d *AccountShareRoomDelete) Where(ps ...predicate.AccountShareRoom) *AccountShareRoomDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountShareRoomDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountShareRoomDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountShareRoomDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountshareroom.Table, sqlgraph.NewFieldSpec(accountshareroom.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountShareRoomDeleteOne is the builder for deleting a single AccountShareRoom entity.
type AccountShareRoomDeleteOne struct {
	_d *AccountShareRoomDelete
}

// Where appends a list predicates to the AccountShareRoomDelete builder.
func (_d *AccountShareRoomDeleteOne) Where(ps ...predicate.AccountShareRoom) *AccountShareRoomDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountShareRoomDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountshareroom.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountShareRoomDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
