// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/your-org/ai-gateway-platform/ent/accountshareroom"
	"github.com/your-org/ai-gateway-platform/ent/predicate"
)

// AccountShareRoomUpdate is the builder for updating AccountShareRoom entities.
type AccountShareRoomUpdate struct {
	config
	hooks    []Hook
	mutation *AccountShareRoomMutation
}

// Where appends a list predicates to the AccountShareRoomUpdate builder.
func (_u *AccountShareRoomUpdate) Where(ps ...predicate.AccountShareRoom) *AccountShareRoomUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountShareRoomUpdate) SetUpdatedAt(v time.Time) *AccountShareRoomUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountShareRoomUpdate) SetAccountID(v int64) *AccountShareRoomUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountShareRoomUpdate) SetNillableAccountID(v *int64) *AccountShareRoomUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountShareRoomUpdate) AddAccountID(v int64) *AccountShareRoomUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *AccountShareRoomUpdate) SetOwnerUserID(v int64) *AccountShareRoomUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *AccountShareRoomUpdate) SetNillableOwnerUserID(v *int64) *AccountShareRoomUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *AccountShareRoomUpdate) AddOwnerUserID(v int64) *AccountShareRoomUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountShareRoomUpdate) SetName(v string) *AccountShareRoomUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountShareRoomUpdate) SetNillableName(v *string) *AccountShareRoomUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountShareRoomUpdate) SetStatus(v string) *AccountShareRoomUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountShareRoomUpdate) SetNillableStatus(v *string) *AccountShareRoomUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSeatLimit sets the "seat_limit" field.
func (_u *AccountShareRoomUpdate) SetSeatLimit(v int) *AccountShareRoomUpdate {
	_u.mutation.ResetSeatLimit()
	_u.mutation.SetSeatLimit(v)
	return _u
}

// SetNillableSeatLimit sets the "seat_limit" field if the given value is not nil.
func (_u *AccountShareRoomUpdate) SetNillableSeatLimit(v *int) *AccountShareRoomUpdate {
	if v != nil {
		_u.SetSeatLimit(*v)
	}
	return _u
}

// AddSeatLimit adds value to the "seat_limit" field.
func (_u *AccountShareRoomUpdate) AddSeatLimit(v int) *AccountShareRoomUpdate {
	_u.mutation.AddSeatLimit(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *AccountShareRoomUpdate) SetRateMultiplier(v float64) *AccountShareRoomUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *AccountShareRoomUpdate) SetNillableRateMultiplier(v *float64) *AccountShareRoomUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *AccountShareRoomUpdate) AddRateMultiplier(v float64) *AccountShareRoomUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetAllowedModels sets the "allowed_models" field.
func (_u *AccountShareRoomUpdate) SetAllowedModels(v []string) *AccountShareRoomUpdate {
	_u.mutation.SetAllowedModels(v)
	return _u
}

// AppendAllowedModels appends value to the "allowed_models" field.
func (_u *AccountShareRoomUpdate) AppendAllowedModels(v []string) *AccountShareRoomUpdate {
	_u.mutation.AppendAllowedModels(v)
	return _u
}

// ClearAllowedModels clears the value of the "allowed_models" field.
func (_u *AccountShareRoomUpdate) ClearAllowedModels() *AccountShareRoomUpdate {
	_u.mutation.ClearAllowedModels()
	return _u
}

// SetPerUserConcurrency sets the "per_user_concurrency" field.
func (_u *AccountShareRoomUpdate) SetPerUserConcurrency(v int) *AccountShareRoomUpdate {
	_u.mutation.ResetPerUserConcurrency()
	_u.mutation.SetPerUserConcurrency(v)
	return _u
}

// SetNillablePerUserConcurrency sets the "per_user_concurrency" field if the given value is not nil.
func (_u *AccountShareRoomUpdate) SetNillablePerUserConcurrency(v *int) *AccountShareRoomUpdate {
	if v != nil {
		_u.SetPerUserConcurrency(*v)
	}
	return _u
}

// AddPerUserConcurrency adds value to the "per_user_concurrency" field.
func (_u *AccountShareRoomUpdate) AddPerUserConcurrency(v int) *AccountShareRoomUpdate {
	_u.mutation.AddPerUserConcurrency(v)
	return _u
}

// SetQueueMax sets the "queue_max" field.
func (_u *AccountShareRoomUpdate) SetQueueMax(v int) *AccountShareRoomUpdate {
	_u.mutation.ResetQueueMax()
	_u.mutation.SetQueueMax(v)
	return _u
}

// SetNillableQueueMax sets the "queue_max" field if the given value is not nil.
func (_u *AccountShareRoomUpdate) SetNillableQueueMax(v *int) *AccountShareRoomUpdate {
	if v != nil {
		_u.SetQueueMax(*v)
	}
	return _u
}

// AddQueueMax adds value to the "queue_max" field.
func (_u *AccountShareRoomUpdate) AddQueueMax(v int) *AccountShareRoomUpdate {
	_u.mutation.AddQueueMax(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *AccountShareRoomUpdate) SetVersion(v int) *AccountShareRoomUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AccountShareRoomUpdate) SetNillableVersion(v *int) *AccountShareRoomUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AccountShareRoomUpdate) AddVersion(v int) *AccountShareRoomUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the AccountShareRoomMutation object of the builder.
func (_u *AccountShareRoomUpdate) Mutation() *AccountShareRoomMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountShareRoomUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountShareRoomUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountShareRoomUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountShareRoomUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountShareRoomUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountshareroom.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountShareRoomUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountshareroom.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountShareRoom.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accountshareroom.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountShareRoom.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountShareRoomUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountshareroom.Table, accountshareroom.Columns, sqlgraph.NewFieldSpec(accountshareroom.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountshareroom.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountshareroom.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountshareroom.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(accountshareroom.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(accountshareroom.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountshareroom.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accountshareroom.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SeatLimit(); ok {
		_spec.SetField(accountshareroom.FieldSeatLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeatLimit(); ok {
		_spec.AddField(accountshareroom.FieldSeatLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(accountshareroom.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(accountshareroom.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AllowedModels(); ok {
		_spec.SetField(accountshareroom.FieldAllowedModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accountshareroom.FieldAllowedModels, value)
		})
	}
	if _u.mutation.AllowedModelsCleared() {
		_spec.ClearField(accountshareroom.FieldAllowedModels, field.TypeJSON)
	}
	if value, ok := _u.mutation.PerUserConcurrency(); ok {
		_spec.SetField(accountshareroom.FieldPerUserConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPerUserConcurrency(); ok {
		_spec.AddField(accountshareroom.FieldPerUserConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QueueMax(); ok {
		_spec.SetField(accountshareroom.FieldQueueMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQueueMax(); ok {
		_spec.AddField(accountshareroom.FieldQueueMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(accountshareroom.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(accountshareroom.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountshareroom.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountShareRoomUpdateOne is the builder for updating a single AccountShareRoom entity.
type AccountShareRoomUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountShareRoomMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountShareRoomUpdateOne) SetUpdatedAt(v time.Time) *AccountShareRoomUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountShareRoomUpdateOne) SetAccountID(v int64) *AccountShareRoomUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountShareRoomUpdateOne) SetNillableAccountID(v *int64) *AccountShareRoomUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountShareRoomUpdateOne) AddAccountID(v int64) *AccountShareRoomUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *AccountShareRoomUpdateOne) SetOwnerUserID(v int64) *AccountShareRoomUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *AccountShareRoomUpdateOne) SetNillableOwnerUserID(v *int64) *AccountShareRoomUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *AccountShareRoomUpdateOne) AddOwnerUserID(v int64) *AccountShareRoomUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountShareRoomUpdateOne) SetName(v string) *AccountShareRoomUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountShareRoomUpdateOne) SetNillableName(v *string) *AccountShareRoomUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountShareRoomUpdateOne) SetStatus(v string) *AccountShareRoomUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountShareRoomUpdateOne) SetNillableStatus(v *string) *AccountShareRoomUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSeatLimit sets the "seat_limit" field.
func (_u *AccountShareRoomUpdateOne) SetSeatLimit(v int) *AccountShareRoomUpdateOne {
	_u.mutation.ResetSeatLimit()
	_u.mutation.SetSeatLimit(v)
	return _u
}

// SetNillableSeatLimit sets the "seat_limit" field if the given value is not nil.
func (_u *AccountShareRoomUpdateOne) SetNillableSeatLimit(v *int) *AccountShareRoomUpdateOne {
	if v != nil {
		_u.SetSeatLimit(*v)
	}
	return _u
}

// AddSeatLimit adds value to the "seat_limit" field.
func (_u *AccountShareRoomUpdateOne) AddSeatLimit(v int) *AccountShareRoomUpdateOne {
	_u.mutation.AddSeatLimit(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *AccountShareRoomUpdateOne) SetRateMultiplier(v float64) *AccountShareRoomUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *AccountShareRoomUpdateOne) SetNillableRateMultiplier(v *float64) *AccountShareRoomUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *AccountShareRoomUpdateOne) AddRateMultiplier(v float64) *AccountShareRoomUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetAllowedModels sets the "allowed_models" field.
func (_u *AccountShareRoomUpdateOne) SetAllowedModels(v []string) *AccountShareRoomUpdateOne {
	_u.mutation.SetAllowedModels(v)
	return _u
}

// AppendAllowedModels appends value to the "allowed_models" field.
func (_u *AccountShareRoomUpdateOne) AppendAllowedModels(v []string) *AccountShareRoomUpdateOne {
	_u.mutation.AppendAllowedModels(v)
	return _u
}

// ClearAllowedModels clears the value of the "allowed_models" field.
func (_u *AccountShareRoomUpdateOne) ClearAllowedModels() *AccountShareRoomUpdateOne {
	_u.mutation.ClearAllowedModels()
	return _u
}

// SetPerUserConcurrency sets the "per_user_concurrency" field.
func (_u *AccountShareRoomUpdateOne) SetPerUserConcurrency(v int) *AccountShareRoomUpdateOne {
	_u.mutation.ResetPerUserConcurrency()
	_u.mutation.SetPerUserConcurrency(v)
	return _u
}

// SetNillablePerUserConcurrency sets the "per_user_concurrency" field if the given value is not nil.
func (_u *AccountShareRoomUpdateOne) SetNillablePerUserConcurrency(v *int) *AccountShareRoomUpdateOne {
	if v != nil {
		_u.SetPerUserConcurrency(*v)
	}
	return _u
}

// AddPerUserConcurrency adds value to the "per_user_concurrency" field.
func (_u *AccountShareRoomUpdateOne) AddPerUserConcurrency(v int) *AccountShareRoomUpdateOne {
	_u.mutation.AddPerUserConcurrency(v)
	return _u
}

// SetQueueMax sets the "queue_max" field.
func (_u *AccountShareRoomUpdateOne) SetQueueMax(v int) *AccountShareRoomUpdateOne {
	_u.mutation.ResetQueueMax()
	_u.mutation.SetQueueMax(v)
	return _u
}

// SetNillableQueueMax sets the "queue_max" field if the given value is not nil.
func (_u *AccountShareRoomUpdateOne) SetNillableQueueMax(v *int) *AccountShareRoomUpdateOne {
	if v != nil {
		_u.SetQueueMax(*v)
	}
	return _u
}

// AddQueueMax adds value to the "queue_max" field.
func (_u *AccountShareRoomUpdateOne) AddQueueMax(v int) *AccountShareRoomUpdateOne {
	_u.mutation.AddQueueMax(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *AccountShareRoomUpdateOne) SetVersion(v int) *AccountShareRoomUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AccountShareRoomUpdateOne) SetNillableVersion(v *int) *AccountShareRoomUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AccountShareRoomUpdateOne) AddVersion(v int) *AccountShareRoomUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the AccountShareRoomMutation object of the builder.
func (_u *AccountShareRoomUpdateOne) Mutation() *AccountShareRoomMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountShareRoomUpdate builder.
func (_u *AccountShareRoomUpdateOne) Where(ps ...predicate.AccountShareRoom) *AccountShareRoomUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountShareRoomUpdateOne) Select(field string, fields ...string) *AccountShareRoomUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountShareRoom entity.
func (_u *AccountShareRoomUpdateOne) Save(ctx context.Context) (*AccountShareRoom, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountShareRoomUpdateOne) SaveX(ctx context.Context) *AccountShareRoom {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountShareRoomUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountShareRoomUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountShareRoomUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountshareroom.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountShareRoomUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountshareroom.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountShareRoom.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accountshareroom.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountShareRoom.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountShareRoomUpdateOne) sqlSave(ctx context.Context) (_node *AccountShareRoom, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountshareroom.Table, accountshareroom.Columns, sqlgraph.NewFieldSpec(accountshareroom.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountShareRoom.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountshareroom.FieldID)
		for _, f := range fields {
			if !accountshareroom.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountshareroom.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountshareroom.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountshareroom.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountshareroom.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(accountshareroom.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(accountshareroom.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountshareroom.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accountshareroom.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SeatLimit(); ok {
		_spec.SetField(accountshareroom.FieldSeatLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeatLimit(); ok {
		_spec.AddField(accountshareroom.FieldSeatLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(accountshareroom.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(accountshareroom.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AllowedModels(); ok {
		_spec.SetField(accountshareroom.FieldAllowedModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accountshareroom.FieldAllowedModels, value)
		})
	}
	if _u.mutation.AllowedModelsCleared() {
		_spec.ClearField(accountshareroom.FieldAllowedModels, field.TypeJSON)
	}
	if value, ok := _u.mutation.PerUserConcurrency(); ok {
		_spec.SetField(accountshareroom.FieldPerUserConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPerUserConcurrency(); ok {
		_spec.AddField(accountshareroom.FieldPerUserConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QueueMax(); ok {
		_spec.SetField(accountshareroom.FieldQueueMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQueueMax(); ok {
		_spec.AddField(accountshareroom.FieldQueueMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(accountshareroom.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(accountshareroom.FieldVersion, field.TypeInt, value)
	}
	_node = &AccountShareRoom{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountshareroom.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
