// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/your-org/ai-gateway-platform/ent/accountshareroom"
)

// AccountShareRoomCreate is the builder for creating a AccountShareRoom entity.
type AccountShareRoomCreate struct {
	config
	mutation *AccountShareRoomMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountShareRoomCreate) SetCreatedAt(v time.Time) *AccountShareRoomCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountShareRoomCreate) SetNillableCreatedAt(v *time.Time) *AccountShareRoomCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountShareRoomCreate) SetUpdatedAt(v time.Time) *AccountShareRoomCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountShareRoomCreate) SetNillableUpdatedAt(v *time.Time) *AccountShareRoomCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountShareRoomCreate) SetAccountID(v int64) *AccountShareRoomCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *AccountShareRoomCreate) SetOwnerUserID(v int64) *AccountShareRoomCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AccountShareRoomCreate) SetName(v string) *AccountShareRoomCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AccountShareRoomCreate) SetStatus(v string) *AccountShareRoomCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AccountShareRoomCreate) SetNillableStatus(v *string) *AccountShareRoomCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSeatLimit sets the "seat_limit" field.
func (_c *AccountShareRoomCreate) SetSeatLimit(v int) *AccountShareRoomCreate {
	_c.mutation.SetSeatLimit(v)
	return _c
}

// SetNillableSeatLimit sets the "seat_limit" field if the given value is not nil.
func (_c *AccountShareRoomCreate) SetNillableSeatLimit(v *int) *AccountShareRoomCreate {
	if v != nil {
		_c.SetSeatLimit(*v)
	}
	return _c
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_c *AccountShareRoomCreate) SetRateMultiplier(v float64) *AccountShareRoomCreate {
	_c.mutation.SetRateMultiplier(v)
	return _c
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_c *AccountShareRoomCreate) SetNillableRateMultiplier(v *float64) *AccountShareRoomCreate {
	if v != nil {
		_c.SetRateMultiplier(*v)
	}
	return _c
}

// SetAllowedModels sets the "allowed_models" field.
func (_c *AccountShareRoomCreate) SetAllowedModels(v []string) *AccountShareRoomCreate {
	_c.mutation.SetAllowedModels(v)
	return _c
}

// SetPerUserConcurrency sets the "per_user_concurrency" field.
func (_c *AccountShareRoomCreate) SetPerUserConcurrency(v int) *AccountShareRoomCreate {
	_c.mutation.SetPerUserConcurrency(v)
	return _c
}

// SetNillablePerUserConcurrency sets the "per_user_concurrency" field if the given value is not nil.
func (_c *AccountShareRoomCreate) SetNillablePerUserConcurrency(v *int) *AccountShareRoomCreate {
	if v != nil {
		_c.SetPerUserConcurrency(*v)
	}
	return _c
}

// SetQueueMax sets the "queue_max" field.
func (_c *AccountShareRoomCreate) SetQueueMax(v int) *AccountShareRoomCreate {
	_c.mutation.SetQueueMax(v)
	return _c
}

// SetNillableQueueMax sets the "queue_max" field if the given value is not nil.
func (_c *AccountShareRoomCreate) SetNillableQueueMax(v *int) *AccountShareRoomCreate {
	if v != nil {
		_c.SetQueueMax(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *AccountShareRoomCreate) SetVersion(v int) *AccountShareRoomCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *AccountShareRoomCreate) SetNillableVersion(v *int) *AccountShareRoomCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// Mutation returns the AccountShareRoomMutation object of the builder.
func (_c *AccountShareRoomCreate) Mutation() *AccountShareRoomMutation {
	return _c.mutation
}

// Save creates the AccountShareRoom in the database.
func (_c *AccountShareRoomCreate) Save(ctx context.Context) (*AccountShareRoom, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountShareRoomCreate) SaveX(ctx context.Context) *AccountShareRoom {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountShareRoomCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountShareRoomCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountShareRoomCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountshareroom.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountshareroom.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := accountshareroom.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SeatLimit(); !ok {
		v := accountshareroom.DefaultSeatLimit
		_c.mutation.SetSeatLimit(v)
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		v := accountshareroom.DefaultRateMultiplier
		_c.mutation.SetRateMultiplier(v)
	}
	if _, ok := _c.mutation.PerUserConcurrency(); !ok {
		v := accountshareroom.DefaultPerUserConcurrency
		_c.mutation.SetPerUserConcurrency(v)
	}
	if _, ok := _c.mutation.QueueMax(); !ok {
		v := accountshareroom.DefaultQueueMax
		_c.mutation.SetQueueMax(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := accountshareroom.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountShareRoomCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountShareRoom.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountShareRoom.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountShareRoom.account_id"`)}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "AccountShareRoom.owner_user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AccountShareRoom.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := accountshareroom.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountShareRoom.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AccountShareRoom.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := accountshareroom.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountShareRoom.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SeatLimit(); !ok {
		return &ValidationError{Name: "seat_limit", err: errors.New(`ent: missing required field "AccountShareRoom.seat_limit"`)}
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		return &ValidationError{Name: "rate_multiplier", err: errors.New(`ent: missing required field "AccountShareRoom.rate_multiplier"`)}
	}
	if _, ok := _c.mutation.PerUserConcurrency(); !ok {
		return &ValidationError{Name: "per_user_concurrency", err: errors.New(`ent: missing required field "AccountShareRoom.per_user_concurrency"`)}
	}
	if _, ok := _c.mutation.QueueMax(); !ok {
		return &ValidationError{Name: "queue_max", err: errors.New(`ent: missing required field "AccountShareRoom.queue_max"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "AccountShareRoom.version"`)}
	}
	return nil
}

func (_c *AccountShareRoomCreate) sqlSave(ctx context.Context) (*AccountShareRoom, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountShareRoomCreate) createSpec() (*AccountShareRoom, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountShareRoom{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountshareroom.Table, sqlgraph.NewFieldSpec(accountshareroom.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountshareroom.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountshareroom.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountshareroom.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(accountshareroom.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(accountshareroom.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(accountshareroom.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SeatLimit(); ok {
		_spec.SetField(accountshareroom.FieldSeatLimit, field.TypeInt, value)
		_node.SeatLimit = value
	}
	if value, ok := _c.mutation.RateMultiplier(); ok {
		_spec.SetField(accountshareroom.FieldRateMultiplier, field.TypeFloat64, value)
		_node.RateMultiplier = value
	}
	if value, ok := _c.mutation.AllowedModels(); ok {
		_spec.SetField(accountshareroom.FieldAllowedModels, field.TypeJSON, value)
		_node.AllowedModels = value
	}
	if value, ok := _c.mutation.PerUserConcurrency(); ok {
		_spec.SetField(accountshareroom.FieldPerUserConcurrency, field.TypeInt, value)
		_node.PerUserConcurrency = value
	}
	if value, ok := _c.mutation.QueueMax(); ok {
		_spec.SetField(accountshareroom.FieldQueueMax, field.TypeInt, value)
		_node.QueueMax = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(accountshareroom.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountShareRoom.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountShareRoomUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountShareRoomCreate) OnConflict(opts ...sql.ConflictOption) *AccountShareRoomUpsertOne {
	_c.conflict = opts
	return &AccountShareRoomUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountShareRoom.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountShareRoomCreate) OnConflictColumns(columns ...string) *AccountShareRoomUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountShareRoomUpsertOne{
		create: _c,
	}
}

type (
	// AccountShareRoomUpsertOne is the builder for "upsert"-ing
	//  one AccountShareRoom node.
	AccountShareRoomUpsertOne struct {
		create *AccountShareRoomCreate
	}

	// AccountShareRoomUpsert is the "OnConflict" setter.
	AccountShareRoomUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountShareRoomUpsert) SetUpdatedAt(v time.Time) *AccountShareRoomUpsert {
	u.Set(accountshareroom.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountShareRoomUpsert) UpdateUpdatedAt() *AccountShareRoomUpsert {
	u.SetExcluded(accountshareroom.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountShareRoomUpsert) SetAccountID(v int64) *AccountShareRoomUpsert {
	u.Set(accountshareroom.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountShareRoomUpsert) UpdateAccountID() *AccountShareRoomUpsert {
	u.SetExcluded(accountshareroom.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountShareRoomUpsert) AddAccountID(v int64) *AccountShareRoomUpsert {
	u.Add(accountshareroom.FieldAccountID, v)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *AccountShareRoomUpsert) SetOwnerUserID(v int64) *AccountShareRoomUpsert {
	u.Set(accountshareroom.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *AccountShareRoomUpsert) UpdateOwnerUserID() *AccountShareRoomUpsert {
	u.SetExcluded(accountshareroom.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *AccountShareRoomUpsert) AddOwnerUserID(v int64) *AccountShareRoomUpsert {
	u.Add(accountshareroom.FieldOwnerUserID, v)
	return u
}

// SetName sets the "name" field.
func (u *AccountShareRoomUpsert) SetName(v string) *AccountShareRoomUpsert {
	u.Set(accountshareroom.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountShareRoomUpsert) UpdateName() *AccountShareRoomUpsert {
	u.SetExcluded(accountshareroom.FieldName)
	return u
}

// SetStatus sets the "status" field.
func (u *AccountShareRoomUpsert) SetStatus(v string) *AccountShareRoomUpsert {
	u.Set(accountshareroom.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountShareRoomUpsert) UpdateStatus() *AccountShareRoomUpsert {
	u.SetExcluded(accountshareroom.FieldStatus)
	return u
}

// SetSeatLimit sets the "seat_limit" field.
func (u *AccountShareRoomUpsert) SetSeatLimit(v int) *AccountShareRoomUpsert {
	u.Set(accountshareroom.FieldSeatLimit, v)
	return u
}

// UpdateSeatLimit sets the "seat_limit" field to the value that was provided on create.
func (u *AccountShareRoomUpsert) UpdateSeatLimit() *AccountShareRoomUpsert {
	u.SetExcluded(accountshareroom.FieldSeatLimit)
	return u
}

// AddSeatLimit adds v to the "seat_limit" field.
func (u *AccountShareRoomUpsert) AddSeatLimit(v int) *AccountShareRoomUpsert {
	u.Add(accountshareroom.FieldSeatLimit, v)
	return u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *AccountShareRoomUpsert) SetRateMultiplier(v float64) *AccountShareRoomUpsert {
	u.Set(accountshareroom.FieldRateMultiplier, v)
	return u
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *AccountShareRoomUpsert) UpdateRateMultiplier() *AccountShareRoomUpsert {
	u.SetExcluded(accountshareroom.FieldRateMultiplier)
	return u
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *AccountShareRoomUpsert) AddRateMultiplier(v float64) *AccountShareRoomUpsert {
	u.Add(accountshareroom.FieldRateMultiplier, v)
	return u
}

// SetAllowedModels sets the "allowed_models" field.
func (u *AccountShareRoomUpsert) SetAllowedModels(v []string) *AccountShareRoomUpsert {
	u.Set(accountshareroom.FieldAllowedModels, v)
	return u
}

// UpdateAllowedModels sets the "allowed_models" field to the value that was provided on create.
func (u *AccountShareRoomUpsert) UpdateAllowedModels() *AccountShareRoomUpsert {
	u.SetExcluded(accountshareroom.FieldAllowedModels)
	return u
}

// ClearAllowedModels clears the value of the "allowed_models" field.
func (u *AccountShareRoomUpsert) ClearAllowedModels() *AccountShareRoomUpsert {
	u.SetNull(accountshareroom.FieldAllowedModels)
	return u
}

// SetPerUserConcurrency sets the "per_user_concurrency" field.
func (u *AccountShareRoomUpsert) SetPerUserConcurrency(v int) *AccountShareRoomUpsert {
	u.Set(accountshareroom.FieldPerUserConcurrency, v)
	return u
}

// UpdatePerUserConcurrency sets the "per_user_concurrency" field to the value that was provided on create.
func (u *AccountShareRoomUpsert) UpdatePerUserConcurrency() *AccountShareRoomUpsert {
	u.SetExcluded(accountshareroom.FieldPerUserConcurrency)
	return u
}

// AddPerUserConcurrency adds v to the "per_user_concurrency" field.
func (u *AccountShareRoomUpsert) AddPerUserConcurrency(v int) *AccountShareRoomUpsert {
	u.Add(accountshareroom.FieldPerUserConcurrency, v)
	return u
}

// SetQueueMax sets the "queue_max" field.
func (u *AccountShareRoomUpsert) SetQueueMax(v int) *AccountShareRoomUpsert {
	u.Set(accountshareroom.FieldQueueMax, v)
	return u
}

// UpdateQueueMax sets the "queue_max" field to the value that was provided on create.
func (u *AccountShareRoomUpsert) UpdateQueueMax() *AccountShareRoomUpsert {
	u.SetExcluded(accountshareroom.FieldQueueMax)
	return u
}

// AddQueueMax adds v to the "queue_max" field.
func (u *AccountShareRoomUpsert) AddQueueMax(v int) *AccountShareRoomUpsert {
	u.Add(accountshareroom.FieldQueueMax, v)
	return u
}

// SetVersion sets the "version" field.
func (u *AccountShareRoomUpsert) SetVersion(v int) *AccountShareRoomUpsert {
	u.Set(accountshareroom.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *AccountShareRoomUpsert) UpdateVersion() *AccountShareRoomUpsert {
	u.SetExcluded(accountshareroom.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *AccountShareRoomUpsert) AddVersion(v int) *AccountShareRoomUpsert {
	u.Add(accountshareroom.FieldVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountShareRoom.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountShareRoomUpsertOne) UpdateNewValues() *AccountShareRoomUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountshareroom.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountShareRoom.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountShareRoomUpsertOne) Ignore() *AccountShareRoomUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountShareRoomUpsertOne) DoNothing() *AccountShareRoomUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountShareRoomCreate.OnConflict
// documentation for more info.
func (u *AccountShareRoomUpsertOne) Update(set func(*AccountShareRoomUpsert)) *AccountShareRoomUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountShareRoomUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountShareRoomUpsertOne) SetUpdatedAt(v time.Time) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountShareRoomUpsertOne) UpdateUpdatedAt() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountShareRoomUpsertOne) SetAccountID(v int64) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountShareRoomUpsertOne) AddAccountID(v int64) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountShareRoomUpsertOne) UpdateAccountID() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateAccountID()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *AccountShareRoomUpsertOne) SetOwnerUserID(v int64) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *AccountShareRoomUpsertOne) AddOwnerUserID(v int64) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *AccountShareRoomUpsertOne) UpdateOwnerUserID() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetName sets the "name" field.
func (u *AccountShareRoomUpsertOne) SetName(v string) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountShareRoomUpsertOne) UpdateName() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *AccountShareRoomUpsertOne) SetStatus(v string) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountShareRoomUpsertOne) UpdateStatus() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateStatus()
	})
}

// SetSeatLimit sets the "seat_limit" field.
func (u *AccountShareRoomUpsertOne) SetSeatLimit(v int) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetSeatLimit(v)
	})
}

// AddSeatLimit adds v to the "seat_limit" field.
func (u *AccountShareRoomUpsertOne) AddSeatLimit(v int) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddSeatLimit(v)
	})
}

// UpdateSeatLimit sets the "seat_limit" field to the value that was provided on create.
func (u *AccountShareRoomUpsertOne) UpdateSeatLimit() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateSeatLimit()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *AccountShareRoomUpsertOne) SetRateMultiplier(v float64) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *AccountShareRoomUpsertOne) AddRateMultiplier(v float64) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *AccountShareRoomUpsertOne) UpdateRateMultiplier() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetAllowedModels sets the "allowed_models" field.
func (u *AccountShareRoomUpsertOne) SetAllowedModels(v []string) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetAllowedModels(v)
	})
}

// UpdateAllowedModels sets the "allowed_models" field to the value that was provided on create.
func (u *AccountShareRoomUpsertOne) UpdateAllowedModels() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateAllowedModels()
	})
}

// ClearAllowedModels clears the value of the "allowed_models" field.
func (u *AccountShareRoomUpsertOne) ClearAllowedModels() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.ClearAllowedModels()
	})
}

// SetPerUserConcurrency sets the "per_user_concurrency" field.
func (u *AccountShareRoomUpsertOne) SetPerUserConcurrency(v int) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetPerUserConcurrency(v)
	})
}

// AddPerUserConcurrency adds v to the "per_user_concurrency" field.
func (u *AccountShareRoomUpsertOne) AddPerUserConcurrency(v int) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddPerUserConcurrency(v)
	})
}

// UpdatePerUserConcurrency sets the "per_user_concurrency" field to the value that was provided on create.
func (u *AccountShareRoomUpsertOne) UpdatePerUserConcurrency() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdatePerUserConcurrency()
	})
}

// SetQueueMax sets the "queue_max" field.
func (u *AccountShareRoomUpsertOne) SetQueueMax(v int) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetQueueMax(v)
	})
}

// AddQueueMax adds v to the "queue_max" field.
func (u *AccountShareRoomUpsertOne) AddQueueMax(v int) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddQueueMax(v)
	})
}

// UpdateQueueMax sets the "queue_max" field to the value that was provided on create.
func (u *AccountShareRoomUpsertOne) UpdateQueueMax() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateQueueMax()
	})
}

// SetVersion sets the "version" field.
func (u *AccountShareRoomUpsertOne) SetVersion(v int) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *AccountShareRoomUpsertOne) AddVersion(v int) *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *AccountShareRoomUpsertOne) UpdateVersion() *AccountShareRoomUpsertOne {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *AccountShareRoomUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountShareRoomCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountShareRoomUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountShareRoomUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountShareRoomUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountShareRoomCreateBulk is the builder for creating many AccountShareRoom entities in bulk.
type AccountShareRoomCreateBulk struct {
	config
	err      error
	builders []*AccountShareRoomCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountShareRoom entities in the database.
func (_c *AccountShareRoomCreateBulk) Save(ctx context.Context) ([]*AccountShareRoom, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountShareRoom, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountShareRoomMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountShareRoomCreateBulk) SaveX(ctx context.Context) []*AccountShareRoom {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountShareRoomCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountShareRoomCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountShareRoom.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountShareRoomUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountShareRoomCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountShareRoomUpsertBulk {
	_c.conflict = opts
	return &AccountShareRoomUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountShareRoom.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountShareRoomCreateBulk) OnConflictColumns(columns ...string) *AccountShareRoomUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountShareRoomUpsertBulk{
		create: _c,
	}
}

// AccountShareRoomUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountShareRoom nodes.
type AccountShareRoomUpsertBulk struct {
	create *AccountShareRoomCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountShareRoom.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountShareRoomUpsertBulk) UpdateNewValues() *AccountShareRoomUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountshareroom.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountShareRoom.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountShareRoomUpsertBulk) Ignore() *AccountShareRoomUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountShareRoomUpsertBulk) DoNothing() *AccountShareRoomUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountShareRoomCreateBulk.OnConflict
// documentation for more info.
func (u *AccountShareRoomUpsertBulk) Update(set func(*AccountShareRoomUpsert)) *AccountShareRoomUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountShareRoomUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountShareRoomUpsertBulk) SetUpdatedAt(v time.Time) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountShareRoomUpsertBulk) UpdateUpdatedAt() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountShareRoomUpsertBulk) SetAccountID(v int64) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountShareRoomUpsertBulk) AddAccountID(v int64) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountShareRoomUpsertBulk) UpdateAccountID() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateAccountID()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *AccountShareRoomUpsertBulk) SetOwnerUserID(v int64) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *AccountShareRoomUpsertBulk) AddOwnerUserID(v int64) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *AccountShareRoomUpsertBulk) UpdateOwnerUserID() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetName sets the "name" field.
func (u *AccountShareRoomUpsertBulk) SetName(v string) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountShareRoomUpsertBulk) UpdateName() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *AccountShareRoomUpsertBulk) SetStatus(v string) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountShareRoomUpsertBulk) UpdateStatus() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateStatus()
	})
}

// SetSeatLimit sets the "seat_limit" field.
func (u *AccountShareRoomUpsertBulk) SetSeatLimit(v int) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetSeatLimit(v)
	})
}

// AddSeatLimit adds v to the "seat_limit" field.
func (u *AccountShareRoomUpsertBulk) AddSeatLimit(v int) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddSeatLimit(v)
	})
}

// UpdateSeatLimit sets the "seat_limit" field to the value that was provided on create.
func (u *AccountShareRoomUpsertBulk) UpdateSeatLimit() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateSeatLimit()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *AccountShareRoomUpsertBulk) SetRateMultiplier(v float64) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *AccountShareRoomUpsertBulk) AddRateMultiplier(v float64) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *AccountShareRoomUpsertBulk) UpdateRateMultiplier() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetAllowedModels sets the "allowed_models" field.
func (u *AccountShareRoomUpsertBulk) SetAllowedModels(v []string) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetAllowedModels(v)
	})
}

// UpdateAllowedModels sets the "allowed_models" field to the value that was provided on create.
func (u *AccountShareRoomUpsertBulk) UpdateAllowedModels() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateAllowedModels()
	})
}

// ClearAllowedModels clears the value of the "allowed_models" field.
func (u *AccountShareRoomUpsertBulk) ClearAllowedModels() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.ClearAllowedModels()
	})
}

// SetPerUserConcurrency sets the "per_user_concurrency" field.
func (u *AccountShareRoomUpsertBulk) SetPerUserConcurrency(v int) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetPerUserConcurrency(v)
	})
}

// AddPerUserConcurrency adds v to the "per_user_concurrency" field.
func (u *AccountShareRoomUpsertBulk) AddPerUserConcurrency(v int) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddPerUserConcurrency(v)
	})
}

// UpdatePerUserConcurrency sets the "per_user_concurrency" field to the value that was provided on create.
func (u *AccountShareRoomUpsertBulk) UpdatePerUserConcurrency() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdatePerUserConcurrency()
	})
}

// SetQueueMax sets the "queue_max" field.
func (u *AccountShareRoomUpsertBulk) SetQueueMax(v int) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetQueueMax(v)
	})
}

// AddQueueMax adds v to the "queue_max" field.
func (u *AccountShareRoomUpsertBulk) AddQueueMax(v int) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddQueueMax(v)
	})
}

// UpdateQueueMax sets the "queue_max" field to the value that was provided on create.
func (u *AccountShareRoomUpsertBulk) UpdateQueueMax() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateQueueMax()
	})
}

// SetVersion sets the "version" field.
func (u *AccountShareRoomUpsertBulk) SetVersion(v int) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *AccountShareRoomUpsertBulk) AddVersion(v int) *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *AccountShareRoomUpsertBulk) UpdateVersion() *AccountShareRoomUpsertBulk {
	return u.Update(func(s *AccountShareRoomUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *AccountShareRoomUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountShareRoomCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountShareRoomCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountShareRoomUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
