// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/your-org/ai-gateway-platform/ent/ownerledger"
	"github.com/your-org/ai-gateway-platform/ent/predicate"
)

// OwnerLedgerDelete is the builder for deleting a OwnerLedger entity.
type OwnerLedgerDelete struct {
	config
	hooks    []Hook
	mutation *OwnerLedgerMutation
}

// Where appends a list predicates to the OwnerLedgerDelete builder.
func (_d *OwnerLedgerDelete) Where(ps ...predicate.OwnerLedger) *OwnerLedgerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OwnerLedgerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OwnerLedgerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OwnerLedgerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ownerledger.Table, sqlgraph.NewFieldSpec(ownerledger.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OwnerLedgerDeleteOne is the builder for deleting a single OwnerLedger entity.
type OwnerLedgerDeleteOne struct {
	_d *OwnerLedgerDelete
}

// Where appends a list predicates to the OwnerLedgerDelete builder.
func (_d *OwnerLedgerDeleteOne) Where(ps ...predicate.OwnerLedger) *OwnerLedgerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OwnerLedgerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ownerledger.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OwnerLedgerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
