// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/your-org/ai-gateway-platform/ent/ownerledger"
)

// OwnerLedgerCreate is the builder for creating a OwnerLedger entity.
type OwnerLedgerCreate struct {
	config
	mutation *OwnerLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OwnerLedgerCreate) SetCreatedAt(v time.Time) *OwnerLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OwnerLedgerCreate) SetNillableCreatedAt(v *time.Time) *OwnerLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OwnerLedgerCreate) SetUpdatedAt(v time.Time) *OwnerLedgerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OwnerLedgerCreate) SetNillableUpdatedAt(v *time.Time) *OwnerLedgerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *OwnerLedgerCreate) SetOwnerUserID(v int64) *OwnerLedgerCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetDirection sets the "direction" field.
func (_c *OwnerLedgerCreate) SetDirection(v ownerledger.Direction) *OwnerLedgerCreate {
	_c.mutation.SetDirection(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *OwnerLedgerCreate) SetAmount(v float64) *OwnerLedgerCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetBalanceBefore sets the "balance_before" field.
func (_c *OwnerLedgerCreate) SetBalanceBefore(v float64) *OwnerLedgerCreate {
	_c.mutation.SetBalanceBefore(v)
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *OwnerLedgerCreate) SetBalanceAfter(v float64) *OwnerLedgerCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetEntryType sets the "entry_type" field.
func (_c *OwnerLedgerCreate) SetEntryType(v string) *OwnerLedgerCreate {
	_c.mutation.SetEntryType(v)
	return _c
}

// SetRefType sets the "ref_type" field.
func (_c *OwnerLedgerCreate) SetRefType(v string) *OwnerLedgerCreate {
	_c.mutation.SetRefType(v)
	return _c
}

// SetNillableRefType sets the "ref_type" field if the given value is not nil.
func (_c *OwnerLedgerCreate) SetNillableRefType(v *string) *OwnerLedgerCreate {
	if v != nil {
		_c.SetRefType(*v)
	}
	return _c
}

// SetRefID sets the "ref_id" field.
func (_c *OwnerLedgerCreate) SetRefID(v int64) *OwnerLedgerCreate {
	_c.mutation.SetRefID(v)
	return _c
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (_c *OwnerLedgerCreate) SetNillableRefID(v *int64) *OwnerLedgerCreate {
	if v != nil {
		_c.SetRefID(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *OwnerLedgerCreate) SetMetadata(v map[string]interface{}) *OwnerLedgerCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// Mutation returns the OwnerLedgerMutation object of the builder.
func (_c *OwnerLedgerCreate) Mutation() *OwnerLedgerMutation {
	return _c.mutation
}

// Save creates the OwnerLedger in the database.
func (_c *OwnerLedgerCreate) Save(ctx context.Context) (*OwnerLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OwnerLedgerCreate) SaveX(ctx context.Context) *OwnerLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OwnerLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OwnerLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OwnerLedgerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ownerledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ownerledger.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OwnerLedgerCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OwnerLedger.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OwnerLedger.updated_at"`)}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "OwnerLedger.owner_user_id"`)}
	}
	if _, ok := _c.mutation.Direction(); !ok {
		return &ValidationError{Name: "direction", err: errors.New(`ent: missing required field "OwnerLedger.direction"`)}
	}
	if v, ok := _c.mutation.Direction(); ok {
		if err := ownerledger.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "OwnerLedger.direction": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "OwnerLedger.amount"`)}
	}
	if _, ok := _c.mutation.BalanceBefore(); !ok {
		return &ValidationError{Name: "balance_before", err: errors.New(`ent: missing required field "OwnerLedger.balance_before"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "OwnerLedger.balance_after"`)}
	}
	if _, ok := _c.mutation.EntryType(); !ok {
		return &ValidationError{Name: "entry_type", err: errors.New(`ent: missing required field "OwnerLedger.entry_type"`)}
	}
	if v, ok := _c.mutation.EntryType(); ok {
		if err := ownerledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "OwnerLedger.entry_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RefType(); ok {
		if err := ownerledger.RefTypeValidator(v); err != nil {
			return &ValidationError{Name: "ref_type", err: fmt.Errorf(`ent: validator failed for field "OwnerLedger.ref_type": %w`, err)}
		}
	}
	return nil
}

func (_c *OwnerLedgerCreate) sqlSave(ctx context.Context) (*OwnerLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OwnerLedgerCreate) createSpec() (*OwnerLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &OwnerLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ownerledger.Table, sqlgraph.NewFieldSpec(ownerledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ownerledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ownerledger.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(ownerledger.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.Direction(); ok {
		_spec.SetField(ownerledger.FieldDirection, field.TypeEnum, value)
		_node.Direction = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(ownerledger.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.BalanceBefore(); ok {
		_spec.SetField(ownerledger.FieldBalanceBefore, field.TypeFloat64, value)
		_node.BalanceBefore = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(ownerledger.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.EntryType(); ok {
		_spec.SetField(ownerledger.FieldEntryType, field.TypeString, value)
		_node.EntryType = value
	}
	if value, ok := _c.mutation.RefType(); ok {
		_spec.SetField(ownerledger.FieldRefType, field.TypeString, value)
		_node.RefType = &value
	}
	if value, ok := _c.mutation.RefID(); ok {
		_spec.SetField(ownerledger.FieldRefID, field.TypeInt64, value)
		_node.RefID = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(ownerledger.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OwnerLedger.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OwnerLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OwnerLedgerCreate) OnConflict(opts ...sql.ConflictOption) *OwnerLedgerUpsertOne {
	_c.conflict = opts
	return &OwnerLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OwnerLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OwnerLedgerCreate) OnConflictColumns(columns ...string) *OwnerLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OwnerLedgerUpsertOne{
		create: _c,
	}
}

type (
	// OwnerLedgerUpsertOne is the builder for "upsert"-ing
	//  one OwnerLedger node.
	OwnerLedgerUpsertOne struct {
		create *OwnerLedgerCreate
	}

	// OwnerLedgerUpsert is the "OnConflict" setter.
	OwnerLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OwnerLedgerUpsert) SetUpdatedAt(v time.Time) *OwnerLedgerUpsert {
	u.Set(ownerledger.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OwnerLedgerUpsert) UpdateUpdatedAt() *OwnerLedgerUpsert {
	u.SetExcluded(ownerledger.FieldUpdatedAt)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *OwnerLedgerUpsert) SetOwnerUserID(v int64) *OwnerLedgerUpsert {
	u.Set(ownerledger.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *OwnerLedgerUpsert) UpdateOwnerUserID() *OwnerLedgerUpsert {
	u.SetExcluded(ownerledger.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *OwnerLedgerUpsert) AddOwnerUserID(v int64) *OwnerLedgerUpsert {
	u.Add(ownerledger.FieldOwnerUserID, v)
	return u
}

// SetDirection sets the "direction" field.
func (u *OwnerLedgerUpsert) SetDirection(v ownerledger.Direction) *OwnerLedgerUpsert {
	u.Set(ownerledger.FieldDirection, v)
	return u
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *OwnerLedgerUpsert) UpdateDirection() *OwnerLedgerUpsert {
	u.SetExcluded(ownerledger.FieldDirection)
	return u
}

// SetAmount sets the "amount" field.
func (u *OwnerLedgerUpsert) SetAmount(v float64) *OwnerLedgerUpsert {
	u.Set(ownerledger.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OwnerLedgerUpsert) UpdateAmount() *OwnerLedgerUpsert {
	u.SetExcluded(ownerledger.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *OwnerLedgerUpsert) AddAmount(v float64) *OwnerLedgerUpsert {
	u.Add(ownerledger.FieldAmount, v)
	return u
}

// SetBalanceBefore sets the "balance_before" field.
func (u *OwnerLedgerUpsert) SetBalanceBefore(v float64) *OwnerLedgerUpsert {
	u.Set(ownerledger.FieldBalanceBefore, v)
	return u
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *OwnerLedgerUpsert) UpdateBalanceBefore() *OwnerLedgerUpsert {
	u.SetExcluded(ownerledger.FieldBalanceBefore)
	return u
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *OwnerLedgerUpsert) AddBalanceBefore(v float64) *OwnerLedgerUpsert {
	u.Add(ownerledger.FieldBalanceBefore, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *OwnerLedgerUpsert) SetBalanceAfter(v float64) *OwnerLedgerUpsert {
	u.Set(ownerledger.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *OwnerLedgerUpsert) UpdateBalanceAfter() *OwnerLedgerUpsert {
	u.SetExcluded(ownerledger.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *OwnerLedgerUpsert) AddBalanceAfter(v float64) *OwnerLedgerUpsert {
	u.Add(ownerledger.FieldBalanceAfter, v)
	return u
}

// SetEntryType sets the "entry_type" field.
func (u *OwnerLedgerUpsert) SetEntryType(v string) *OwnerLedgerUpsert {
	u.Set(ownerledger.FieldEntryType, v)
	return u
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *OwnerLedgerUpsert) UpdateEntryType() *OwnerLedgerUpsert {
	u.SetExcluded(ownerledger.FieldEntryType)
	return u
}

// SetRefType sets the "ref_type" field.
func (u *OwnerLedgerUpsert) SetRefType(v string) *OwnerLedgerUpsert {
	u.Set(ownerledger.FieldRefType, v)
	return u
}

// UpdateRefType sets the "ref_type" field to the value that was provided on create.
func (u *OwnerLedgerUpsert) UpdateRefType() *OwnerLedgerUpsert {
	u.SetExcluded(ownerledger.FieldRefType)
	return u
}

// ClearRefType clears the value of the "ref_type" field.
func (u *OwnerLedgerUpsert) ClearRefType() *OwnerLedgerUpsert {
	u.SetNull(ownerledger.FieldRefType)
	return u
}

// SetRefID sets the "ref_id" field.
func (u *OwnerLedgerUpsert) SetRefID(v int64) *OwnerLedgerUpsert {
	u.Set(ownerledger.FieldRefID, v)
	return u
}

// UpdateRefID sets the "ref_id" field to the value that was provided on create.
func (u *OwnerLedgerUpsert) UpdateRefID() *OwnerLedgerUpsert {
	u.SetExcluded(ownerledger.FieldRefID)
	return u
}

// AddRefID adds v to the "ref_id" field.
func (u *OwnerLedgerUpsert) AddRefID(v int64) *OwnerLedgerUpsert {
	u.Add(ownerledger.FieldRefID, v)
	return u
}

// ClearRefID clears the value of the "ref_id" field.
func (u *OwnerLedgerUpsert) ClearRefID() *OwnerLedgerUpsert {
	u.SetNull(ownerledger.FieldRefID)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *OwnerLedgerUpsert) SetMetadata(v map[string]interface{}) *OwnerLedgerUpsert {
	u.Set(ownerledger.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *OwnerLedgerUpsert) UpdateMetadata() *OwnerLedgerUpsert {
	u.SetExcluded(ownerledger.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *OwnerLedgerUpsert) ClearMetadata() *OwnerLedgerUpsert {
	u.SetNull(ownerledger.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OwnerLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OwnerLedgerUpsertOne) UpdateNewValues() *OwnerLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ownerledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OwnerLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OwnerLedgerUpsertOne) Ignore() *OwnerLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OwnerLedgerUpsertOne) DoNothing() *OwnerLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OwnerLedgerCreate.OnConflict
// documentation for more info.
func (u *OwnerLedgerUpsertOne) Update(set func(*OwnerLedgerUpsert)) *OwnerLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OwnerLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OwnerLedgerUpsertOne) SetUpdatedAt(v time.Time) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OwnerLedgerUpsertOne) UpdateUpdatedAt() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *OwnerLedgerUpsertOne) SetOwnerUserID(v int64) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *OwnerLedgerUpsertOne) AddOwnerUserID(v int64) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *OwnerLedgerUpsertOne) UpdateOwnerUserID() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetDirection sets the "direction" field.
func (u *OwnerLedgerUpsertOne) SetDirection(v ownerledger.Direction) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *OwnerLedgerUpsertOne) UpdateDirection() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateDirection()
	})
}

// SetAmount sets the "amount" field.
func (u *OwnerLedgerUpsertOne) SetAmount(v float64) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *OwnerLedgerUpsertOne) AddAmount(v float64) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OwnerLedgerUpsertOne) UpdateAmount() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *OwnerLedgerUpsertOne) SetBalanceBefore(v float64) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetBalanceBefore(v)
	})
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *OwnerLedgerUpsertOne) AddBalanceBefore(v float64) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.AddBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *OwnerLedgerUpsertOne) UpdateBalanceBefore() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *OwnerLedgerUpsertOne) SetBalanceAfter(v float64) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *OwnerLedgerUpsertOne) AddBalanceAfter(v float64) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *OwnerLedgerUpsertOne) UpdateBalanceAfter() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *OwnerLedgerUpsertOne) SetEntryType(v string) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *OwnerLedgerUpsertOne) UpdateEntryType() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateEntryType()
	})
}

// SetRefType sets the "ref_type" field.
func (u *OwnerLedgerUpsertOne) SetRefType(v string) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetRefType(v)
	})
}

// UpdateRefType sets the "ref_type" field to the value that was provided on create.
func (u *OwnerLedgerUpsertOne) UpdateRefType() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateRefType()
	})
}

// ClearRefType clears the value of the "ref_type" field.
func (u *OwnerLedgerUpsertOne) ClearRefType() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.ClearRefType()
	})
}

// SetRefID sets the "ref_id" field.
func (u *OwnerLedgerUpsertOne) SetRefID(v int64) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetRefID(v)
	})
}

// AddRefID adds v to the "ref_id" field.
func (u *OwnerLedgerUpsertOne) AddRefID(v int64) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.AddRefID(v)
	})
}

// UpdateRefID sets the "ref_id" field to the value that was provided on create.
func (u *OwnerLedgerUpsertOne) UpdateRefID() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateRefID()
	})
}

// ClearRefID clears the value of the "ref_id" field.
func (u *OwnerLedgerUpsertOne) ClearRefID() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.ClearRefID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *OwnerLedgerUpsertOne) SetMetadata(v map[string]interface{}) *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *OwnerLedgerUpsertOne) UpdateMetadata() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *OwnerLedgerUpsertOne) ClearMetadata() *OwnerLedgerUpsertOne {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *OwnerLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OwnerLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OwnerLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OwnerLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OwnerLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OwnerLedgerCreateBulk is the builder for creating many OwnerLedger entities in bulk.
type OwnerLedgerCreateBulk struct {
	config
	err      error
	builders []*OwnerLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the OwnerLedger entities in the database.
func (_c *OwnerLedgerCreateBulk) Save(ctx context.Context) ([]*OwnerLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OwnerLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OwnerLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OwnerLedgerCreateBulk) SaveX(ctx context.Context) []*OwnerLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OwnerLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OwnerLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OwnerLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OwnerLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OwnerLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *OwnerLedgerUpsertBulk {
	_c.conflict = opts
	return &OwnerLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OwnerLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OwnerLedgerCreateBulk) OnConflictColumns(columns ...string) *OwnerLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OwnerLedgerUpsertBulk{
		create: _c,
	}
}

// OwnerLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of OwnerLedger nodes.
type OwnerLedgerUpsertBulk struct {
	create *OwnerLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OwnerLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OwnerLedgerUpsertBulk) UpdateNewValues() *OwnerLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ownerledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OwnerLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OwnerLedgerUpsertBulk) Ignore() *OwnerLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OwnerLedgerUpsertBulk) DoNothing() *OwnerLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OwnerLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *OwnerLedgerUpsertBulk) Update(set func(*OwnerLedgerUpsert)) *OwnerLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OwnerLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OwnerLedgerUpsertBulk) SetUpdatedAt(v time.Time) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OwnerLedgerUpsertBulk) UpdateUpdatedAt() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *OwnerLedgerUpsertBulk) SetOwnerUserID(v int64) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *OwnerLedgerUpsertBulk) AddOwnerUserID(v int64) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *OwnerLedgerUpsertBulk) UpdateOwnerUserID() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetDirection sets the "direction" field.
func (u *OwnerLedgerUpsertBulk) SetDirection(v ownerledger.Direction) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *OwnerLedgerUpsertBulk) UpdateDirection() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateDirection()
	})
}

// SetAmount sets the "amount" field.
func (u *OwnerLedgerUpsertBulk) SetAmount(v float64) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *OwnerLedgerUpsertBulk) AddAmount(v float64) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OwnerLedgerUpsertBulk) UpdateAmount() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *OwnerLedgerUpsertBulk) SetBalanceBefore(v float64) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetBalanceBefore(v)
	})
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *OwnerLedgerUpsertBulk) AddBalanceBefore(v float64) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.AddBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *OwnerLedgerUpsertBulk) UpdateBalanceBefore() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *OwnerLedgerUpsertBulk) SetBalanceAfter(v float64) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *OwnerLedgerUpsertBulk) AddBalanceAfter(v float64) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *OwnerLedgerUpsertBulk) UpdateBalanceAfter() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *OwnerLedgerUpsertBulk) SetEntryType(v string) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *OwnerLedgerUpsertBulk) UpdateEntryType() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateEntryType()
	})
}

// SetRefType sets the "ref_type" field.
func (u *OwnerLedgerUpsertBulk) SetRefType(v string) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetRefType(v)
	})
}

// UpdateRefType sets the "ref_type" field to the value that was provided on create.
func (u *OwnerLedgerUpsertBulk) UpdateRefType() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateRefType()
	})
}

// ClearRefType clears the value of the "ref_type" field.
func (u *OwnerLedgerUpsertBulk) ClearRefType() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.ClearRefType()
	})
}

// SetRefID sets the "ref_id" field.
func (u *OwnerLedgerUpsertBulk) SetRefID(v int64) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetRefID(v)
	})
}

// AddRefID adds v to the "ref_id" field.
func (u *OwnerLedgerUpsertBulk) AddRefID(v int64) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.AddRefID(v)
	})
}

// UpdateRefID sets the "ref_id" field to the value that was provided on create.
func (u *OwnerLedgerUpsertBulk) UpdateRefID() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateRefID()
	})
}

// ClearRefID clears the value of the "ref_id" field.
func (u *OwnerLedgerUpsertBulk) ClearRefID() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.ClearRefID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *OwnerLedgerUpsertBulk) SetMetadata(v map[string]interface{}) *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *OwnerLedgerUpsertBulk) UpdateMetadata() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *OwnerLedgerUpsertBulk) ClearMetadata() *OwnerLedgerUpsertBulk {
	return u.Update(func(s *OwnerLedgerUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *OwnerLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OwnerLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OwnerLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OwnerLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
