// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/your-org/ai-gateway-platform/ent/ownerledger"
	"github.com/your-org/ai-gateway-platform/ent/predicate"
)

// OwnerLedgerUpdate is the builder for updating OwnerLedger entities.
type OwnerLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *OwnerLedgerMutation
}

// Where appends a list predicates to the OwnerLedgerUpdate builder.
func (_u *OwnerLedgerUpdate) Where(ps ...predicate.OwnerLedger) *OwnerLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OwnerLedgerUpdate) SetUpdatedAt(v time.Time) *OwnerLedgerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *OwnerLedgerUpdate) SetOwnerUserID(v int64) *OwnerLedgerUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *OwnerLedgerUpdate) SetNillableOwnerUserID(v *int64) *OwnerLedgerUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *OwnerLedgerUpdate) AddOwnerUserID(v int64) *OwnerLedgerUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetDirection sets the "direction" field.
func (_u *OwnerLedgerUpdate) SetDirection(v ownerledger.Direction) *OwnerLedgerUpdate {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *OwnerLedgerUpdate) SetNillableDirection(v *ownerledger.Direction) *OwnerLedgerUpdate {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *OwnerLedgerUpdate) SetAmount(v float64) *OwnerLedgerUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *OwnerLedgerUpdate) SetNillableAmount(v *float64) *OwnerLedgerUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *OwnerLedgerUpdate) AddAmount(v float64) *OwnerLedgerUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *OwnerLedgerUpdate) SetBalanceBefore(v float64) *OwnerLedgerUpdate {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *OwnerLedgerUpdate) SetNillableBalanceBefore(v *float64) *OwnerLedgerUpdate {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *OwnerLedgerUpdate) AddBalanceBefore(v float64) *OwnerLedgerUpdate {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *OwnerLedgerUpdate) SetBalanceAfter(v float64) *OwnerLedgerUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *OwnerLedgerUpdate) SetNillableBalanceAfter(v *float64) *OwnerLedgerUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *OwnerLedgerUpdate) AddBalanceAfter(v float64) *OwnerLedgerUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *OwnerLedgerUpdate) SetEntryType(v string) *OwnerLedgerUpdate {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *OwnerLedgerUpdate) SetNillableEntryType(v *string) *OwnerLedgerUpdate {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetRefType sets the "ref_type" field.
func (_u *OwnerLedgerUpdate) SetRefType(v string) *OwnerLedgerUpdate {
	_u.mutation.SetRefType(v)
	return _u
}

// SetNillableRefType sets the "ref_type" field if the given value is not nil.
func (_u *OwnerLedgerUpdate) SetNillableRefType(v *string) *OwnerLedgerUpdate {
	if v != nil {
		_u.SetRefType(*v)
	}
	return _u
}

// ClearRefType clears the value of the "ref_type" field.
func (_u *OwnerLedgerUpdate) ClearRefType() *OwnerLedgerUpdate {
	_u.mutation.ClearRefType()
	return _u
}

// SetRefID sets the "ref_id" field.
func (_u *OwnerLedgerUpdate) SetRefID(v int64) *OwnerLedgerUpdate {
	_u.mutation.ResetRefID()
	_u.mutation.SetRefID(v)
	return _u
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (_u *OwnerLedgerUpdate) SetNillableRefID(v *int64) *OwnerLedgerUpdate {
	if v != nil {
		_u.SetRefID(*v)
	}
	return _u
}

// AddRefID adds value to the "ref_id" field.
func (_u *OwnerLedgerUpdate) AddRefID(v int64) *OwnerLedgerUpdate {
	_u.mutation.AddRefID(v)
	return _u
}

// ClearRefID clears the value of the "ref_id" field.
func (_u *OwnerLedgerUpdate) ClearRefID() *OwnerLedgerUpdate {
	_u.mutation.ClearRefID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *OwnerLedgerUpdate) SetMetadata(v map[string]interface{}) *OwnerLedgerUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *OwnerLedgerUpdate) ClearMetadata() *OwnerLedgerUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the OwnerLedgerMutation object of the builder.
func (_u *OwnerLedgerUpdate) Mutation() *OwnerLedgerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OwnerLedgerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OwnerLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OwnerLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OwnerLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OwnerLedgerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ownerledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OwnerLedgerUpdate) check() error {
	if v, ok := _u.mutation.Direction(); ok {
		if err := ownerledger.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "OwnerLedger.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntryType(); ok {
		if err := ownerledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "OwnerLedger.entry_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefType(); ok {
		if err := ownerledger.RefTypeValidator(v); err != nil {
			return &ValidationError{Name: "ref_type", err: fmt.Errorf(`ent: validator failed for field "OwnerLedger.ref_type": %w`, err)}
		}
	}
	return nil
}

func (_u *OwnerLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ownerledger.Table, ownerledger.Columns, sqlgraph.NewFieldSpec(ownerledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ownerledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(ownerledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(ownerledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(ownerledger.FieldDirection, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(ownerledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(ownerledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(ownerledger.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(ownerledger.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(ownerledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(ownerledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(ownerledger.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefType(); ok {
		_spec.SetField(ownerledger.FieldRefType, field.TypeString, value)
	}
	if _u.mutation.RefTypeCleared() {
		_spec.ClearField(ownerledger.FieldRefType, field.TypeString)
	}
	if value, ok := _u.mutation.RefID(); ok {
		_spec.SetField(ownerledger.FieldRefID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefID(); ok {
		_spec.AddField(ownerledger.FieldRefID, field.TypeInt64, value)
	}
	if _u.mutation.RefIDCleared() {
		_spec.ClearField(ownerledger.FieldRefID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(ownerledger.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(ownerledger.FieldMetadata, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ownerledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OwnerLedgerUpdateOne is the builder for updating a single OwnerLedger entity.
type OwnerLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OwnerLedgerMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OwnerLedgerUpdateOne) SetUpdatedAt(v time.Time) *OwnerLedgerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *OwnerLedgerUpdateOne) SetOwnerUserID(v int64) *OwnerLedgerUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *OwnerLedgerUpdateOne) SetNillableOwnerUserID(v *int64) *OwnerLedgerUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *OwnerLedgerUpdateOne) AddOwnerUserID(v int64) *OwnerLedgerUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetDirection sets the "direction" field.
func (_u *OwnerLedgerUpdateOne) SetDirection(v ownerledger.Direction) *OwnerLedgerUpdateOne {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *OwnerLedgerUpdateOne) SetNillableDirection(v *ownerledger.Direction) *OwnerLedgerUpdateOne {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *OwnerLedgerUpdateOne) SetAmount(v float64) *OwnerLedgerUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *OwnerLedgerUpdateOne) SetNillableAmount(v *float64) *OwnerLedgerUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *OwnerLedgerUpdateOne) AddAmount(v float64) *OwnerLedgerUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *OwnerLedgerUpdateOne) SetBalanceBefore(v float64) *OwnerLedgerUpdateOne {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *OwnerLedgerUpdateOne) SetNillableBalanceBefore(v *float64) *OwnerLedgerUpdateOne {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *OwnerLedgerUpdateOne) AddBalanceBefore(v float64) *OwnerLedgerUpdateOne {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *OwnerLedgerUpdateOne) SetBalanceAfter(v float64) *OwnerLedgerUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *OwnerLedgerUpdateOne) SetNillableBalanceAfter(v *float64) *OwnerLedgerUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *OwnerLedgerUpdateOne) AddBalanceAfter(v float64) *OwnerLedgerUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *OwnerLedgerUpdateOne) SetEntryType(v string) *OwnerLedgerUpdateOne {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *OwnerLedgerUpdateOne) SetNillableEntryType(v *string) *OwnerLedgerUpdateOne {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetRefType sets the "ref_type" field.
func (_u *OwnerLedgerUpdateOne) SetRefType(v string) *OwnerLedgerUpdateOne {
	_u.mutation.SetRefType(v)
	return _u
}

// SetNillableRefType sets the "ref_type" field if the given value is not nil.
func (_u *OwnerLedgerUpdateOne) SetNillableRefType(v *string) *OwnerLedgerUpdateOne {
	if v != nil {
		_u.SetRefType(*v)
	}
	return _u
}

// ClearRefType clears the value of the "ref_type" field.
func (_u *OwnerLedgerUpdateOne) ClearRefType() *OwnerLedgerUpdateOne {
	_u.mutation.ClearRefType()
	return _u
}

// SetRefID sets the "ref_id" field.
func (_u *OwnerLedgerUpdateOne) SetRefID(v int64) *OwnerLedgerUpdateOne {
	_u.mutation.ResetRefID()
	_u.mutation.SetRefID(v)
	return _u
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (_u *OwnerLedgerUpdateOne) SetNillableRefID(v *int64) *OwnerLedgerUpdateOne {
	if v != nil {
		_u.SetRefID(*v)
	}
	return _u
}

// AddRefID adds value to the "ref_id" field.
func (_u *OwnerLedgerUpdateOne) AddRefID(v int64) *OwnerLedgerUpdateOne {
	_u.mutation.AddRefID(v)
	return _u
}

// ClearRefID clears the value of the "ref_id" field.
func (_u *OwnerLedgerUpdateOne) ClearRefID() *OwnerLedgerUpdateOne {
	_u.mutation.ClearRefID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *OwnerLedgerUpdateOne) SetMetadata(v map[string]interface{}) *OwnerLedgerUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *OwnerLedgerUpdateOne) ClearMetadata() *OwnerLedgerUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the OwnerLedgerMutation object of the builder.
func (_u *OwnerLedgerUpdateOne) Mutation() *OwnerLedgerMutation {
	return _u.mutation
}

// Where appends a list predicates to the OwnerLedgerUpdate builder.
func (_u *OwnerLedgerUpdateOne) Where(ps ...predicate.OwnerLedger) *OwnerLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OwnerLedgerUpdateOne) Select(field string, fields ...string) *OwnerLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OwnerLedger entity.
func (_u *OwnerLedgerUpdateOne) Save(ctx context.Context) (*OwnerLedger, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OwnerLedgerUpdateOne) SaveX(ctx context.Context) *OwnerLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OwnerLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OwnerLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OwnerLedgerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ownerledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OwnerLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.Direction(); ok {
		if err := ownerledger.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "OwnerLedger.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntryType(); ok {
		if err := ownerledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "OwnerLedger.entry_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefType(); ok {
		if err := ownerledger.RefTypeValidator(v); err != nil {
			return &ValidationError{Name: "ref_type", err: fmt.Errorf(`ent: validator failed for field "OwnerLedger.ref_type": %w`, err)}
		}
	}
	return nil
}

func (_u *OwnerLedgerUpdateOne) sqlSave(ctx context.Context) (_node *OwnerLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ownerledger.Table, ownerledger.Columns, sqlgraph.NewFieldSpec(ownerledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OwnerLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ownerledger.FieldID)
		for _, f := range fields {
			if !ownerledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ownerledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ownerledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(ownerledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(ownerledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(ownerledger.FieldDirection, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(ownerledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(ownerledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(ownerledger.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(ownerledger.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(ownerledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(ownerledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(ownerledger.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefType(); ok {
		_spec.SetField(ownerledger.FieldRefType, field.TypeString, value)
	}
	if _u.mutation.RefTypeCleared() {
		_spec.ClearField(ownerledger.FieldRefType, field.TypeString)
	}
	if value, ok := _u.mutation.RefID(); ok {
		_spec.SetField(ownerledger.FieldRefID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefID(); ok {
		_spec.AddField(ownerledger.FieldRefID, field.TypeInt64, value)
	}
	if _u.mutation.RefIDCleared() {
		_spec.ClearField(ownerledger.FieldRefID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(ownerledger.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(ownerledger.FieldMetadata, field.TypeJSON)
	}
	_node = &OwnerLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ownerledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
