// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/your-org/ai-gateway-platform/ent/settlement"
)

// Settlement is the model entity for the Settlement schema.
type Settlement struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// SettlementNo holds the value of the "settlement_no" field.
	SettlementNo string `json:"settlement_no,omitempty"`
	// PeriodStart holds the value of the "period_start" field.
	PeriodStart time.Time `json:"period_start,omitempty"`
	// PeriodEnd holds the value of the "period_end" field.
	PeriodEnd time.Time `json:"period_end,omitempty"`
	// GrossAmount holds the value of the "gross_amount" field.
	GrossAmount float64 `json:"gross_amount,omitempty"`
	// FeeAmount holds the value of the "fee_amount" field.
	FeeAmount float64 `json:"fee_amount,omitempty"`
	// NetAmount holds the value of the "net_amount" field.
	NetAmount float64 `json:"net_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt    *time.Time `json:"settled_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Settlement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case settlement.FieldGrossAmount, settlement.FieldFeeAmount, settlement.FieldNetAmount:
			values[i] = new(sql.NullFloat64)
		case settlement.FieldID, settlement.FieldOwnerUserID:
			values[i] = new(sql.NullInt64)
		case settlement.FieldSettlementNo, settlement.FieldStatus:
			values[i] = new(sql.NullString)
		case settlement.FieldCreatedAt, settlement.FieldUpdatedAt, settlement.FieldPeriodStart, settlement.FieldPeriodEnd, settlement.FieldSettledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Settlement fields.
func (_m *Settlement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case settlement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case settlement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case settlement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case settlement.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case settlement.FieldSettlementNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_no", values[i])
			} else if value.Valid {
				_m.SettlementNo = value.String
			}
		case settlement.FieldPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_start", values[i])
			} else if value.Valid {
				_m.PeriodStart = value.Time
			}
		case settlement.FieldPeriodEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_end", values[i])
			} else if value.Valid {
				_m.PeriodEnd = value.Time
			}
		case settlement.FieldGrossAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field gross_amount", values[i])
			} else if value.Valid {
				_m.GrossAmount = value.Float64
			}
		case settlement.FieldFeeAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_amount", values[i])
			} else if value.Valid {
				_m.FeeAmount = value.Float64
			}
		case settlement.FieldNetAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field net_amount", values[i])
			} else if value.Valid {
				_m.NetAmount = value.Float64
			}
		case settlement.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case settlement.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Settlement.
// This includes values selected through modifiers, order, etc.
func (_m *Settlement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Settlement.
// Note that you need to call Settlement.Unwrap() before calling this method if this Settlement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Settlement) Update() *SettlementUpdateOne {
	return NewSettlementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Settlement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Settlement) Unwrap() *Settlement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Settlement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Settlement) String() string {
	var builder strings.Builder
	builder.WriteString("Settlement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	builder.WriteString("settlement_no=")
	builder.WriteString(_m.SettlementNo)
	builder.WriteString(", ")
	builder.WriteString("period_start=")
	builder.WriteString(_m.PeriodStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("period_end=")
	builder.WriteString(_m.PeriodEnd.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("gross_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrossAmount))
	builder.WriteString(", ")
	builder.WriteString("fee_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeeAmount))
	builder.WriteString(", ")
	builder.WriteString("net_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Settlements is a parsable slice of Settlement.
type Settlements []*Settlement
