// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/your-org/ai-gateway-platform/ent/settlement"
)

// SettlementCreate is the builder for creating a Settlement entity.
type SettlementCreate struct {
	config
	mutation *SettlementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SettlementCreate) SetCreatedAt(v time.Time) *SettlementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableCreatedAt(v *time.Time) *SettlementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SettlementCreate) SetUpdatedAt(v time.Time) *SettlementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableUpdatedAt(v *time.Time) *SettlementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *SettlementCreate) SetOwnerUserID(v int64) *SettlementCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetSettlementNo sets the "settlement_no" field.
func (_c *SettlementCreate) SetSettlementNo(v string) *SettlementCreate {
	_c.mutation.SetSettlementNo(v)
	return _c
}

// SetPeriodStart sets the "period_start" field.
func (_c *SettlementCreate) SetPeriodStart(v time.Time) *SettlementCreate {
	_c.mutation.SetPeriodStart(v)
	return _c
}

// SetPeriodEnd sets the "period_end" field.
func (_c *SettlementCreate) SetPeriodEnd(v time.Time) *SettlementCreate {
	_c.mutation.SetPeriodEnd(v)
	return _c
}

// SetGrossAmount sets the "gross_amount" field.
func (_c *SettlementCreate) SetGrossAmount(v float64) *SettlementCreate {
	_c.mutation.SetGrossAmount(v)
	return _c
}

// SetNillableGrossAmount sets the "gross_amount" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableGrossAmount(v *float64) *SettlementCreate {
	if v != nil {
		_c.SetGrossAmount(*v)
	}
	return _c
}

// SetFeeAmount sets the "fee_amount" field.
func (_c *SettlementCreate) SetFeeAmount(v float64) *SettlementCreate {
	_c.mutation.SetFeeAmount(v)
	return _c
}

// SetNillableFeeAmount sets the "fee_amount" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableFeeAmount(v *float64) *SettlementCreate {
	if v != nil {
		_c.SetFeeAmount(*v)
	}
	return _c
}

// SetNetAmount sets the "net_amount" field.
func (_c *SettlementCreate) SetNetAmount(v float64) *SettlementCreate {
	_c.mutation.SetNetAmount(v)
	return _c
}

// SetNillableNetAmount sets the "net_amount" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableNetAmount(v *float64) *SettlementCreate {
	if v != nil {
		_c.SetNetAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SettlementCreate) SetStatus(v string) *SettlementCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableStatus(v *string) *SettlementCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSettledAt sets the "settled_at" field.
func (_c *SettlementCreate) SetSettledAt(v time.Time) *SettlementCreate {
	_c.mutation.SetSettledAt(v)
	return _c
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableSettledAt(v *time.Time) *SettlementCreate {
	if v != nil {
		_c.SetSettledAt(*v)
	}
	return _c
}

// Mutation returns the SettlementMutation object of the builder.
func (_c *SettlementCreate) Mutation() *SettlementMutation {
	return _c.mutation
}

// Save creates the Settlement in the database.
func (_c *SettlementCreate) Save(ctx context.Context) (*Settlement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SettlementCreate) SaveX(ctx context.Context) *Settlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettlementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettlementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SettlementCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := settlement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := settlement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.GrossAmount(); !ok {
		v := settlement.DefaultGrossAmount
		_c.mutation.SetGrossAmount(v)
	}
	if _, ok := _c.mutation.FeeAmount(); !ok {
		v := settlement.DefaultFeeAmount
		_c.mutation.SetFeeAmount(v)
	}
	if _, ok := _c.mutation.NetAmount(); !ok {
		v := settlement.DefaultNetAmount
		_c.mutation.SetNetAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := settlement.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SettlementCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Settlement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Settlement.updated_at"`)}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "Settlement.owner_user_id"`)}
	}
	if _, ok := _c.mutation.SettlementNo(); !ok {
		return &ValidationError{Name: "settlement_no", err: errors.New(`ent: missing required field "Settlement.settlement_no"`)}
	}
	if v, ok := _c.mutation.SettlementNo(); ok {
		if err := settlement.SettlementNoValidator(v); err != nil {
			return &ValidationError{Name: "settlement_no", err: fmt.Errorf(`ent: validator failed for field "Settlement.settlement_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeriodStart(); !ok {
		return &ValidationError{Name: "period_start", err: errors.New(`ent: missing required field "Settlement.period_start"`)}
	}
	if _, ok := _c.mutation.PeriodEnd(); !ok {
		return &ValidationError{Name: "period_end", err: errors.New(`ent: missing required field "Settlement.period_end"`)}
	}
	if _, ok := _c.mutation.GrossAmount(); !ok {
		return &ValidationError{Name: "gross_amount", err: errors.New(`ent: missing required field "Settlement.gross_amount"`)}
	}
	if _, ok := _c.mutation.FeeAmount(); !ok {
		return &ValidationError{Name: "fee_amount", err: errors.New(`ent: missing required field "Settlement.fee_amount"`)}
	}
	if _, ok := _c.mutation.NetAmount(); !ok {
		return &ValidationError{Name: "net_amount", err: errors.New(`ent: missing required field "Settlement.net_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Settlement.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := settlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Settlement.status": %w`, err)}
		}
	}
	return nil
}

func (_c *SettlementCreate) sqlSave(ctx context.Context) (*Settlement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SettlementCreate) createSpec() (*Settlement, *sqlgraph.CreateSpec) {
	var (
		_node = &Settlement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(settlement.Table, sqlgraph.NewFieldSpec(settlement.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(settlement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(settlement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(settlement.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.SettlementNo(); ok {
		_spec.SetField(settlement.FieldSettlementNo, field.TypeString, value)
		_node.SettlementNo = value
	}
	if value, ok := _c.mutation.PeriodStart(); ok {
		_spec.SetField(settlement.FieldPeriodStart, field.TypeTime, value)
		_node.PeriodStart = value
	}
	if value, ok := _c.mutation.PeriodEnd(); ok {
		_spec.SetField(settlement.FieldPeriodEnd, field.TypeTime, value)
		_node.PeriodEnd = value
	}
	if value, ok := _c.mutation.GrossAmount(); ok {
		_spec.SetField(settlement.FieldGrossAmount, field.TypeFloat64, value)
		_node.GrossAmount = value
	}
	if value, ok := _c.mutation.FeeAmount(); ok {
		_spec.SetField(settlement.FieldFeeAmount, field.TypeFloat64, value)
		_node.FeeAmount = value
	}
	if value, ok := _c.mutation.NetAmount(); ok {
		_spec.SetField(settlement.FieldNetAmount, field.TypeFloat64, value)
		_node.NetAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(settlement.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SettledAt(); ok {
		_spec.SetField(settlement.FieldSettledAt, field.TypeTime, value)
		_node.SettledAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Settlement.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SettlementUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SettlementCreate) OnConflict(opts ...sql.ConflictOption) *SettlementUpsertOne {
	_c.conflict = opts
	return &SettlementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Settlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SettlementCreate) OnConflictColumns(columns ...string) *SettlementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SettlementUpsertOne{
		create: _c,
	}
}

type (
	// SettlementUpsertOne is the builder for "upsert"-ing
	//  one Settlement node.
	SettlementUpsertOne struct {
		create *SettlementCreate
	}

	// SettlementUpsert is the "OnConflict" setter.
	SettlementUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SettlementUpsert) SetUpdatedAt(v time.Time) *SettlementUpsert {
	u.Set(settlement.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SettlementUpsert) UpdateUpdatedAt() *SettlementUpsert {
	u.SetExcluded(settlement.FieldUpdatedAt)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *SettlementUpsert) SetOwnerUserID(v int64) *SettlementUpsert {
	u.Set(settlement.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *SettlementUpsert) UpdateOwnerUserID() *SettlementUpsert {
	u.SetExcluded(settlement.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *SettlementUpsert) AddOwnerUserID(v int64) *SettlementUpsert {
	u.Add(settlement.FieldOwnerUserID, v)
	return u
}

// SetSettlementNo sets the "settlement_no" field.
func (u *SettlementUpsert) SetSettlementNo(v string) *SettlementUpsert {
	u.Set(settlement.FieldSettlementNo, v)
	return u
}

// UpdateSettlementNo sets the "settlement_no" field to the value that was provided on create.
func (u *SettlementUpsert) UpdateSettlementNo() *SettlementUpsert {
	u.SetExcluded(settlement.FieldSettlementNo)
	return u
}

// SetPeriodStart sets the "period_start" field.
func (u *SettlementUpsert) SetPeriodStart(v time.Time) *SettlementUpsert {
	u.Set(settlement.FieldPeriodStart, v)
	return u
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *SettlementUpsert) UpdatePeriodStart() *SettlementUpsert {
	u.SetExcluded(settlement.FieldPeriodStart)
	return u
}

// SetPeriodEnd sets the "period_end" field.
func (u *SettlementUpsert) SetPeriodEnd(v time.Time) *SettlementUpsert {
	u.Set(settlement.FieldPeriodEnd, v)
	return u
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *SettlementUpsert) UpdatePeriodEnd() *SettlementUpsert {
	u.SetExcluded(settlement.FieldPeriodEnd)
	return u
}

// SetGrossAmount sets the "gross_amount" field.
func (u *SettlementUpsert) SetGrossAmount(v float64) *SettlementUpsert {
	u.Set(settlement.FieldGrossAmount, v)
	return u
}

// UpdateGrossAmount sets the "gross_amount" field to the value that was provided on create.
func (u *SettlementUpsert) UpdateGrossAmount() *SettlementUpsert {
	u.SetExcluded(settlement.FieldGrossAmount)
	return u
}

// AddGrossAmount adds v to the "gross_amount" field.
func (u *SettlementUpsert) AddGrossAmount(v float64) *SettlementUpsert {
	u.Add(settlement.FieldGrossAmount, v)
	return u
}

// SetFeeAmount sets the "fee_amount" field.
func (u *SettlementUpsert) SetFeeAmount(v float64) *SettlementUpsert {
	u.Set(settlement.FieldFeeAmount, v)
	return u
}

// UpdateFeeAmount sets the "fee_amount" field to the value that was provided on create.
func (u *SettlementUpsert) UpdateFeeAmount() *SettlementUpsert {
	u.SetExcluded(settlement.FieldFeeAmount)
	return u
}

// AddFeeAmount adds v to the "fee_amount" field.
func (u *SettlementUpsert) AddFeeAmount(v float64) *SettlementUpsert {
	u.Add(settlement.FieldFeeAmount, v)
	return u
}

// SetNetAmount sets the "net_amount" field.
func (u *SettlementUpsert) SetNetAmount(v float64) *SettlementUpsert {
	u.Set(settlement.FieldNetAmount, v)
	return u
}

// UpdateNetAmount sets the "net_amount" field to the value that was provided on create.
func (u *SettlementUpsert) UpdateNetAmount() *SettlementUpsert {
	u.SetExcluded(settlement.FieldNetAmount)
	return u
}

// AddNetAmount adds v to the "net_amount" field.
func (u *SettlementUpsert) AddNetAmount(v float64) *SettlementUpsert {
	u.Add(settlement.FieldNetAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *SettlementUpsert) SetStatus(v string) *SettlementUpsert {
	u.Set(settlement.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SettlementUpsert) UpdateStatus() *SettlementUpsert {
	u.SetExcluded(settlement.FieldStatus)
	return u
}

// SetSettledAt sets the "settled_at" field.
func (u *SettlementUpsert) SetSettledAt(v time.Time) *SettlementUpsert {
	u.Set(settlement.FieldSettledAt, v)
	return u
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *SettlementUpsert) UpdateSettledAt() *SettlementUpsert {
	u.SetExcluded(settlement.FieldSettledAt)
	return u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *SettlementUpsert) ClearSettledAt() *SettlementUpsert {
	u.SetNull(settlement.FieldSettledAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Settlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SettlementUpsertOne) UpdateNewValues() *SettlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(settlement.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Settlement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SettlementUpsertOne) Ignore() *SettlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SettlementUpsertOne) DoNothing() *SettlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SettlementCreate.OnConflict
// documentation for more info.
func (u *SettlementUpsertOne) Update(set func(*SettlementUpsert)) *SettlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SettlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SettlementUpsertOne) SetUpdatedAt(v time.Time) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SettlementUpsertOne) UpdateUpdatedAt() *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *SettlementUpsertOne) SetOwnerUserID(v int64) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *SettlementUpsertOne) AddOwnerUserID(v int64) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *SettlementUpsertOne) UpdateOwnerUserID() *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetSettlementNo sets the "settlement_no" field.
func (u *SettlementUpsertOne) SetSettlementNo(v string) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.SetSettlementNo(v)
	})
}

// UpdateSettlementNo sets the "settlement_no" field to the value that was provided on create.
func (u *SettlementUpsertOne) UpdateSettlementNo() *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateSettlementNo()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *SettlementUpsertOne) SetPeriodStart(v time.Time) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *SettlementUpsertOne) UpdatePeriodStart() *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *SettlementUpsertOne) SetPeriodEnd(v time.Time) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *SettlementUpsertOne) UpdatePeriodEnd() *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetGrossAmount sets the "gross_amount" field.
func (u *SettlementUpsertOne) SetGrossAmount(v float64) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.SetGrossAmount(v)
	})
}

// AddGrossAmount adds v to the "gross_amount" field.
func (u *SettlementUpsertOne) AddGrossAmount(v float64) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.AddGrossAmount(v)
	})
}

// UpdateGrossAmount sets the "gross_amount" field to the value that was provided on create.
func (u *SettlementUpsertOne) UpdateGrossAmount() *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateGrossAmount()
	})
}

// SetFeeAmount sets the "fee_amount" field.
func (u *SettlementUpsertOne) SetFeeAmount(v float64) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.SetFeeAmount(v)
	})
}

// AddFeeAmount adds v to the "fee_amount" field.
func (u *SettlementUpsertOne) AddFeeAmount(v float64) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.AddFeeAmount(v)
	})
}

// UpdateFeeAmount sets the "fee_amount" field to the value that was provided on create.
func (u *SettlementUpsertOne) UpdateFeeAmount() *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateFeeAmount()
	})
}

// SetNetAmount sets the "net_amount" field.
func (u *SettlementUpsertOne) SetNetAmount(v float64) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.SetNetAmount(v)
	})
}

// AddNetAmount adds v to the "net_amount" field.
func (u *SettlementUpsertOne) AddNetAmount(v float64) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.AddNetAmount(v)
	})
}

// UpdateNetAmount sets the "net_amount" field to the value that was provided on create.
func (u *SettlementUpsertOne) UpdateNetAmount() *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateNetAmount()
	})
}

// SetStatus sets the "status" field.
func (u *SettlementUpsertOne) SetStatus(v string) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SettlementUpsertOne) UpdateStatus() *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateStatus()
	})
}

// SetSettledAt sets the "settled_at" field.
func (u *SettlementUpsertOne) SetSettledAt(v time.Time) *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.SetSettledAt(v)
	})
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *SettlementUpsertOne) UpdateSettledAt() *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateSettledAt()
	})
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *SettlementUpsertOne) ClearSettledAt() *SettlementUpsertOne {
	return u.Update(func(s *SettlementUpsert) {
		s.ClearSettledAt()
	})
}

// Exec executes the query.
func (u *SettlementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SettlementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SettlementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SettlementUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SettlementUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SettlementCreateBulk is the builder for creating many Settlement entities in bulk.
type SettlementCreateBulk struct {
	config
	err      error
	builders []*SettlementCreate
	conflict []sql.ConflictOption
}

// Save creates the Settlement entities in the database.
func (_c *SettlementCreateBulk) Save(ctx context.Context) ([]*Settlement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Settlement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SettlementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SettlementCreateBulk) SaveX(ctx context.Context) []*Settlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettlementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettlementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Settlement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SettlementUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SettlementCreateBulk) OnConflict(opts ...sql.ConflictOption) *SettlementUpsertBulk {
	_c.conflict = opts
	return &SettlementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Settlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SettlementCreateBulk) OnConflictColumns(columns ...string) *SettlementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SettlementUpsertBulk{
		create: _c,
	}
}

// SettlementUpsertBulk is the builder for "upsert"-ing
// a bulk of Settlement nodes.
type SettlementUpsertBulk struct {
	create *SettlementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Settlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SettlementUpsertBulk) UpdateNewValues() *SettlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(settlement.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Settlement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SettlementUpsertBulk) Ignore() *SettlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SettlementUpsertBulk) DoNothing() *SettlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SettlementCreateBulk.OnConflict
// documentation for more info.
func (u *SettlementUpsertBulk) Update(set func(*SettlementUpsert)) *SettlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SettlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SettlementUpsertBulk) SetUpdatedAt(v time.Time) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SettlementUpsertBulk) UpdateUpdatedAt() *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *SettlementUpsertBulk) SetOwnerUserID(v int64) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *SettlementUpsertBulk) AddOwnerUserID(v int64) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *SettlementUpsertBulk) UpdateOwnerUserID() *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetSettlementNo sets the "settlement_no" field.
func (u *SettlementUpsertBulk) SetSettlementNo(v string) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.SetSettlementNo(v)
	})
}

// UpdateSettlementNo sets the "settlement_no" field to the value that was provided on create.
func (u *SettlementUpsertBulk) UpdateSettlementNo() *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateSettlementNo()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *SettlementUpsertBulk) SetPeriodStart(v time.Time) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *SettlementUpsertBulk) UpdatePeriodStart() *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *SettlementUpsertBulk) SetPeriodEnd(v time.Time) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *SettlementUpsertBulk) UpdatePeriodEnd() *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetGrossAmount sets the "gross_amount" field.
func (u *SettlementUpsertBulk) SetGrossAmount(v float64) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.SetGrossAmount(v)
	})
}

// AddGrossAmount adds v to the "gross_amount" field.
func (u *SettlementUpsertBulk) AddGrossAmount(v float64) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.AddGrossAmount(v)
	})
}

// UpdateGrossAmount sets the "gross_amount" field to the value that was provided on create.
func (u *SettlementUpsertBulk) UpdateGrossAmount() *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateGrossAmount()
	})
}

// SetFeeAmount sets the "fee_amount" field.
func (u *SettlementUpsertBulk) SetFeeAmount(v float64) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.SetFeeAmount(v)
	})
}

// AddFeeAmount adds v to the "fee_amount" field.
func (u *SettlementUpsertBulk) AddFeeAmount(v float64) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.AddFeeAmount(v)
	})
}

// UpdateFeeAmount sets the "fee_amount" field to the value that was provided on create.
func (u *SettlementUpsertBulk) UpdateFeeAmount() *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateFeeAmount()
	})
}

// SetNetAmount sets the "net_amount" field.
func (u *SettlementUpsertBulk) SetNetAmount(v float64) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.SetNetAmount(v)
	})
}

// AddNetAmount adds v to the "net_amount" field.
func (u *SettlementUpsertBulk) AddNetAmount(v float64) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.AddNetAmount(v)
	})
}

// UpdateNetAmount sets the "net_amount" field to the value that was provided on create.
func (u *SettlementUpsertBulk) UpdateNetAmount() *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateNetAmount()
	})
}

// SetStatus sets the "status" field.
func (u *SettlementUpsertBulk) SetStatus(v string) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SettlementUpsertBulk) UpdateStatus() *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateStatus()
	})
}

// SetSettledAt sets the "settled_at" field.
func (u *SettlementUpsertBulk) SetSettledAt(v time.Time) *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.SetSettledAt(v)
	})
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *SettlementUpsertBulk) UpdateSettledAt() *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.UpdateSettledAt()
	})
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *SettlementUpsertBulk) ClearSettledAt() *SettlementUpsertBulk {
	return u.Update(func(s *SettlementUpsert) {
		s.ClearSettledAt()
	})
}

// Exec executes the query.
func (u *SettlementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SettlementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SettlementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SettlementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
