// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/your-org/ai-gateway-platform/ent/sharepolicy"
)

// SharePolicyCreate is the builder for creating a SharePolicy entity.
type SharePolicyCreate struct {
	config
	mutation *SharePolicyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SharePolicyCreate) SetCreatedAt(v time.Time) *SharePolicyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableCreatedAt(v *time.Time) *SharePolicyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SharePolicyCreate) SetUpdatedAt(v time.Time) *SharePolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableUpdatedAt(v *time.Time) *SharePolicyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SharePolicyCreate) SetDeletedAt(v time.Time) *SharePolicyCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableDeletedAt(v *time.Time) *SharePolicyCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetScopeType sets the "scope_type" field.
func (_c *SharePolicyCreate) SetScopeType(v string) *SharePolicyCreate {
	_c.mutation.SetScopeType(v)
	return _c
}

// SetScopeID sets the "scope_id" field.
func (_c *SharePolicyCreate) SetScopeID(v int64) *SharePolicyCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableScopeID(v *int64) *SharePolicyCreate {
	if v != nil {
		_c.SetScopeID(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *SharePolicyCreate) SetPlatform(v string) *SharePolicyCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillablePlatform(v *string) *SharePolicyCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetOwnerShareRatio sets the "owner_share_ratio" field.
func (_c *SharePolicyCreate) SetOwnerShareRatio(v float64) *SharePolicyCreate {
	_c.mutation.SetOwnerShareRatio(v)
	return _c
}

// SetInviteShareRatio sets the "invite_share_ratio" field.
func (_c *SharePolicyCreate) SetInviteShareRatio(v float64) *SharePolicyCreate {
	_c.mutation.SetInviteShareRatio(v)
	return _c
}

// SetNillableInviteShareRatio sets the "invite_share_ratio" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableInviteShareRatio(v *float64) *SharePolicyCreate {
	if v != nil {
		_c.SetInviteShareRatio(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *SharePolicyCreate) SetVersion(v int) *SharePolicyCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableVersion(v *int) *SharePolicyCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *SharePolicyCreate) SetEnabled(v bool) *SharePolicyCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableEnabled(v *bool) *SharePolicyCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetEffectiveAt sets the "effective_at" field.
func (_c *SharePolicyCreate) SetEffectiveAt(v time.Time) *SharePolicyCreate {
	_c.mutation.SetEffectiveAt(v)
	return _c
}

// SetNillableEffectiveAt sets the "effective_at" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableEffectiveAt(v *time.Time) *SharePolicyCreate {
	if v != nil {
		_c.SetEffectiveAt(*v)
	}
	return _c
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (_c *SharePolicyCreate) SetCreatedByAdminID(v int64) *SharePolicyCreate {
	_c.mutation.SetCreatedByAdminID(v)
	return _c
}

// SetNillableCreatedByAdminID sets the "created_by_admin_id" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableCreatedByAdminID(v *int64) *SharePolicyCreate {
	if v != nil {
		_c.SetCreatedByAdminID(*v)
	}
	return _c
}

// Mutation returns the SharePolicyMutation object of the builder.
func (_c *SharePolicyCreate) Mutation() *SharePolicyMutation {
	return _c.mutation
}

// Save creates the SharePolicy in the database.
func (_c *SharePolicyCreate) Save(ctx context.Context) (*SharePolicy, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SharePolicyCreate) SaveX(ctx context.Context) *SharePolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharePolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharePolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SharePolicyCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sharepolicy.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharepolicy.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sharepolicy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if sharepolicy.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharepolicy.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharepolicy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.InviteShareRatio(); !ok {
		v := sharepolicy.DefaultInviteShareRatio
		_c.mutation.SetInviteShareRatio(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := sharepolicy.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := sharepolicy.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SharePolicyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SharePolicy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SharePolicy.updated_at"`)}
	}
	if _, ok := _c.mutation.ScopeType(); !ok {
		return &ValidationError{Name: "scope_type", err: errors.New(`ent: missing required field "SharePolicy.scope_type"`)}
	}
	if v, ok := _c.mutation.ScopeType(); ok {
		if err := sharepolicy.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.scope_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := sharepolicy.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerShareRatio(); !ok {
		return &ValidationError{Name: "owner_share_ratio", err: errors.New(`ent: missing required field "SharePolicy.owner_share_ratio"`)}
	}
	if v, ok := _c.mutation.OwnerShareRatio(); ok {
		if err := sharepolicy.OwnerShareRatioValidator(v); err != nil {
			return &ValidationError{Name: "owner_share_ratio", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.owner_share_ratio": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InviteShareRatio(); !ok {
		return &ValidationError{Name: "invite_share_ratio", err: errors.New(`ent: missing required field "SharePolicy.invite_share_ratio"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "SharePolicy.version"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "SharePolicy.enabled"`)}
	}
	return nil
}

func (_c *SharePolicyCreate) sqlSave(ctx context.Context) (*SharePolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SharePolicyCreate) createSpec() (*SharePolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &SharePolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sharepolicy.Table, sqlgraph.NewFieldSpec(sharepolicy.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sharepolicy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sharepolicy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sharepolicy.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.ScopeType(); ok {
		_spec.SetField(sharepolicy.FieldScopeType, field.TypeString, value)
		_node.ScopeType = value
	}
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(sharepolicy.FieldScopeID, field.TypeInt64, value)
		_node.ScopeID = &value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(sharepolicy.FieldPlatform, field.TypeString, value)
		_node.Platform = &value
	}
	if value, ok := _c.mutation.OwnerShareRatio(); ok {
		_spec.SetField(sharepolicy.FieldOwnerShareRatio, field.TypeFloat64, value)
		_node.OwnerShareRatio = value
	}
	if value, ok := _c.mutation.InviteShareRatio(); ok {
		_spec.SetField(sharepolicy.FieldInviteShareRatio, field.TypeFloat64, value)
		_node.InviteShareRatio = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(sharepolicy.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(sharepolicy.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.EffectiveAt(); ok {
		_spec.SetField(sharepolicy.FieldEffectiveAt, field.TypeTime, value)
		_node.EffectiveAt = &value
	}
	if value, ok := _c.mutation.CreatedByAdminID(); ok {
		_spec.SetField(sharepolicy.FieldCreatedByAdminID, field.TypeInt64, value)
		_node.CreatedByAdminID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharePolicy.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharePolicyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SharePolicyCreate) OnConflict(opts ...sql.ConflictOption) *SharePolicyUpsertOne {
	_c.conflict = opts
	return &SharePolicyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharePolicyCreate) OnConflictColumns(columns ...string) *SharePolicyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharePolicyUpsertOne{
		create: _c,
	}
}

type (
	// SharePolicyUpsertOne is the builder for "upsert"-ing
	//  one SharePolicy node.
	SharePolicyUpsertOne struct {
		create *SharePolicyCreate
	}

	// SharePolicyUpsert is the "OnConflict" setter.
	SharePolicyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SharePolicyUpsert) SetUpdatedAt(v time.Time) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateUpdatedAt() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharePolicyUpsert) SetDeletedAt(v time.Time) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateDeletedAt() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharePolicyUpsert) ClearDeletedAt() *SharePolicyUpsert {
	u.SetNull(sharepolicy.FieldDeletedAt)
	return u
}

// SetScopeType sets the "scope_type" field.
func (u *SharePolicyUpsert) SetScopeType(v string) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldScopeType, v)
	return u
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateScopeType() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldScopeType)
	return u
}

// SetScopeID sets the "scope_id" field.
func (u *SharePolicyUpsert) SetScopeID(v int64) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldScopeID, v)
	return u
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateScopeID() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldScopeID)
	return u
}

// AddScopeID adds v to the "scope_id" field.
func (u *SharePolicyUpsert) AddScopeID(v int64) *SharePolicyUpsert {
	u.Add(sharepolicy.FieldScopeID, v)
	return u
}

// ClearScopeID clears the value of the "scope_id" field.
func (u *SharePolicyUpsert) ClearScopeID() *SharePolicyUpsert {
	u.SetNull(sharepolicy.FieldScopeID)
	return u
}

// SetPlatform sets the "platform" field.
func (u *SharePolicyUpsert) SetPlatform(v string) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdatePlatform() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldPlatform)
	return u
}

// ClearPlatform clears the value of the "platform" field.
func (u *SharePolicyUpsert) ClearPlatform() *SharePolicyUpsert {
	u.SetNull(sharepolicy.FieldPlatform)
	return u
}

// SetOwnerShareRatio sets the "owner_share_ratio" field.
func (u *SharePolicyUpsert) SetOwnerShareRatio(v float64) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldOwnerShareRatio, v)
	return u
}

// UpdateOwnerShareRatio sets the "owner_share_ratio" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateOwnerShareRatio() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldOwnerShareRatio)
	return u
}

// AddOwnerShareRatio adds v to the "owner_share_ratio" field.
func (u *SharePolicyUpsert) AddOwnerShareRatio(v float64) *SharePolicyUpsert {
	u.Add(sharepolicy.FieldOwnerShareRatio, v)
	return u
}

// SetInviteShareRatio sets the "invite_share_ratio" field.
func (u *SharePolicyUpsert) SetInviteShareRatio(v float64) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldInviteShareRatio, v)
	return u
}

// UpdateInviteShareRatio sets the "invite_share_ratio" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateInviteShareRatio() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldInviteShareRatio)
	return u
}

// AddInviteShareRatio adds v to the "invite_share_ratio" field.
func (u *SharePolicyUpsert) AddInviteShareRatio(v float64) *SharePolicyUpsert {
	u.Add(sharepolicy.FieldInviteShareRatio, v)
	return u
}

// SetVersion sets the "version" field.
func (u *SharePolicyUpsert) SetVersion(v int) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateVersion() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *SharePolicyUpsert) AddVersion(v int) *SharePolicyUpsert {
	u.Add(sharepolicy.FieldVersion, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *SharePolicyUpsert) SetEnabled(v bool) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateEnabled() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldEnabled)
	return u
}

// SetEffectiveAt sets the "effective_at" field.
func (u *SharePolicyUpsert) SetEffectiveAt(v time.Time) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldEffectiveAt, v)
	return u
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateEffectiveAt() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldEffectiveAt)
	return u
}

// ClearEffectiveAt clears the value of the "effective_at" field.
func (u *SharePolicyUpsert) ClearEffectiveAt() *SharePolicyUpsert {
	u.SetNull(sharepolicy.FieldEffectiveAt)
	return u
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (u *SharePolicyUpsert) SetCreatedByAdminID(v int64) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldCreatedByAdminID, v)
	return u
}

// UpdateCreatedByAdminID sets the "created_by_admin_id" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateCreatedByAdminID() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldCreatedByAdminID)
	return u
}

// AddCreatedByAdminID adds v to the "created_by_admin_id" field.
func (u *SharePolicyUpsert) AddCreatedByAdminID(v int64) *SharePolicyUpsert {
	u.Add(sharepolicy.FieldCreatedByAdminID, v)
	return u
}

// ClearCreatedByAdminID clears the value of the "created_by_admin_id" field.
func (u *SharePolicyUpsert) ClearCreatedByAdminID() *SharePolicyUpsert {
	u.SetNull(sharepolicy.FieldCreatedByAdminID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharePolicyUpsertOne) UpdateNewValues() *SharePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sharepolicy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SharePolicyUpsertOne) Ignore() *SharePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharePolicyUpsertOne) DoNothing() *SharePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharePolicyCreate.OnConflict
// documentation for more info.
func (u *SharePolicyUpsertOne) Update(set func(*SharePolicyUpsert)) *SharePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharePolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharePolicyUpsertOne) SetUpdatedAt(v time.Time) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateUpdatedAt() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharePolicyUpsertOne) SetDeletedAt(v time.Time) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateDeletedAt() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharePolicyUpsertOne) ClearDeletedAt() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *SharePolicyUpsertOne) SetScopeType(v string) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateScopeType() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateScopeType()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *SharePolicyUpsertOne) SetScopeID(v int64) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetScopeID(v)
	})
}

// AddScopeID adds v to the "scope_id" field.
func (u *SharePolicyUpsertOne) AddScopeID(v int64) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateScopeID() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateScopeID()
	})
}

// ClearScopeID clears the value of the "scope_id" field.
func (u *SharePolicyUpsertOne) ClearScopeID() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearScopeID()
	})
}

// SetPlatform sets the "platform" field.
func (u *SharePolicyUpsertOne) SetPlatform(v string) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdatePlatform() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdatePlatform()
	})
}

// ClearPlatform clears the value of the "platform" field.
func (u *SharePolicyUpsertOne) ClearPlatform() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearPlatform()
	})
}

// SetOwnerShareRatio sets the "owner_share_ratio" field.
func (u *SharePolicyUpsertOne) SetOwnerShareRatio(v float64) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetOwnerShareRatio(v)
	})
}

// AddOwnerShareRatio adds v to the "owner_share_ratio" field.
func (u *SharePolicyUpsertOne) AddOwnerShareRatio(v float64) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddOwnerShareRatio(v)
	})
}

// UpdateOwnerShareRatio sets the "owner_share_ratio" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateOwnerShareRatio() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateOwnerShareRatio()
	})
}

// SetInviteShareRatio sets the "invite_share_ratio" field.
func (u *SharePolicyUpsertOne) SetInviteShareRatio(v float64) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetInviteShareRatio(v)
	})
}

// AddInviteShareRatio adds v to the "invite_share_ratio" field.
func (u *SharePolicyUpsertOne) AddInviteShareRatio(v float64) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddInviteShareRatio(v)
	})
}

// UpdateInviteShareRatio sets the "invite_share_ratio" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateInviteShareRatio() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateInviteShareRatio()
	})
}

// SetVersion sets the "version" field.
func (u *SharePolicyUpsertOne) SetVersion(v int) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SharePolicyUpsertOne) AddVersion(v int) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateVersion() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateVersion()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SharePolicyUpsertOne) SetEnabled(v bool) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateEnabled() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateEnabled()
	})
}

// SetEffectiveAt sets the "effective_at" field.
func (u *SharePolicyUpsertOne) SetEffectiveAt(v time.Time) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetEffectiveAt(v)
	})
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateEffectiveAt() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateEffectiveAt()
	})
}

// ClearEffectiveAt clears the value of the "effective_at" field.
func (u *SharePolicyUpsertOne) ClearEffectiveAt() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearEffectiveAt()
	})
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (u *SharePolicyUpsertOne) SetCreatedByAdminID(v int64) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetCreatedByAdminID(v)
	})
}

// AddCreatedByAdminID adds v to the "created_by_admin_id" field.
func (u *SharePolicyUpsertOne) AddCreatedByAdminID(v int64) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddCreatedByAdminID(v)
	})
}

// UpdateCreatedByAdminID sets the "created_by_admin_id" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateCreatedByAdminID() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateCreatedByAdminID()
	})
}

// ClearCreatedByAdminID clears the value of the "created_by_admin_id" field.
func (u *SharePolicyUpsertOne) ClearCreatedByAdminID() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearCreatedByAdminID()
	})
}

// Exec executes the query.
func (u *SharePolicyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharePolicyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharePolicyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SharePolicyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SharePolicyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SharePolicyCreateBulk is the builder for creating many SharePolicy entities in bulk.
type SharePolicyCreateBulk struct {
	config
	err      error
	builders []*SharePolicyCreate
	conflict []sql.ConflictOption
}

// Save creates the SharePolicy entities in the database.
func (_c *SharePolicyCreateBulk) Save(ctx context.Context) ([]*SharePolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SharePolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SharePolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SharePolicyCreateBulk) SaveX(ctx context.Context) []*SharePolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharePolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharePolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharePolicy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharePolicyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SharePolicyCreateBulk) OnConflict(opts ...sql.ConflictOption) *SharePolicyUpsertBulk {
	_c.conflict = opts
	return &SharePolicyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharePolicyCreateBulk) OnConflictColumns(columns ...string) *SharePolicyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharePolicyUpsertBulk{
		create: _c,
	}
}

// SharePolicyUpsertBulk is the builder for "upsert"-ing
// a bulk of SharePolicy nodes.
type SharePolicyUpsertBulk struct {
	create *SharePolicyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharePolicyUpsertBulk) UpdateNewValues() *SharePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sharepolicy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SharePolicyUpsertBulk) Ignore() *SharePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharePolicyUpsertBulk) DoNothing() *SharePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharePolicyCreateBulk.OnConflict
// documentation for more info.
func (u *SharePolicyUpsertBulk) Update(set func(*SharePolicyUpsert)) *SharePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharePolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharePolicyUpsertBulk) SetUpdatedAt(v time.Time) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateUpdatedAt() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharePolicyUpsertBulk) SetDeletedAt(v time.Time) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateDeletedAt() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharePolicyUpsertBulk) ClearDeletedAt() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *SharePolicyUpsertBulk) SetScopeType(v string) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateScopeType() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateScopeType()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *SharePolicyUpsertBulk) SetScopeID(v int64) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetScopeID(v)
	})
}

// AddScopeID adds v to the "scope_id" field.
func (u *SharePolicyUpsertBulk) AddScopeID(v int64) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateScopeID() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateScopeID()
	})
}

// ClearScopeID clears the value of the "scope_id" field.
func (u *SharePolicyUpsertBulk) ClearScopeID() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearScopeID()
	})
}

// SetPlatform sets the "platform" field.
func (u *SharePolicyUpsertBulk) SetPlatform(v string) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdatePlatform() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdatePlatform()
	})
}

// ClearPlatform clears the value of the "platform" field.
func (u *SharePolicyUpsertBulk) ClearPlatform() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearPlatform()
	})
}

// SetOwnerShareRatio sets the "owner_share_ratio" field.
func (u *SharePolicyUpsertBulk) SetOwnerShareRatio(v float64) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetOwnerShareRatio(v)
	})
}

// AddOwnerShareRatio adds v to the "owner_share_ratio" field.
func (u *SharePolicyUpsertBulk) AddOwnerShareRatio(v float64) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddOwnerShareRatio(v)
	})
}

// UpdateOwnerShareRatio sets the "owner_share_ratio" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateOwnerShareRatio() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateOwnerShareRatio()
	})
}

// SetInviteShareRatio sets the "invite_share_ratio" field.
func (u *SharePolicyUpsertBulk) SetInviteShareRatio(v float64) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetInviteShareRatio(v)
	})
}

// AddInviteShareRatio adds v to the "invite_share_ratio" field.
func (u *SharePolicyUpsertBulk) AddInviteShareRatio(v float64) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddInviteShareRatio(v)
	})
}

// UpdateInviteShareRatio sets the "invite_share_ratio" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateInviteShareRatio() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateInviteShareRatio()
	})
}

// SetVersion sets the "version" field.
func (u *SharePolicyUpsertBulk) SetVersion(v int) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SharePolicyUpsertBulk) AddVersion(v int) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateVersion() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateVersion()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SharePolicyUpsertBulk) SetEnabled(v bool) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateEnabled() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateEnabled()
	})
}

// SetEffectiveAt sets the "effective_at" field.
func (u *SharePolicyUpsertBulk) SetEffectiveAt(v time.Time) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetEffectiveAt(v)
	})
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateEffectiveAt() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateEffectiveAt()
	})
}

// ClearEffectiveAt clears the value of the "effective_at" field.
func (u *SharePolicyUpsertBulk) ClearEffectiveAt() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearEffectiveAt()
	})
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (u *SharePolicyUpsertBulk) SetCreatedByAdminID(v int64) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetCreatedByAdminID(v)
	})
}

// AddCreatedByAdminID adds v to the "created_by_admin_id" field.
func (u *SharePolicyUpsertBulk) AddCreatedByAdminID(v int64) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddCreatedByAdminID(v)
	})
}

// UpdateCreatedByAdminID sets the "created_by_admin_id" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateCreatedByAdminID() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateCreatedByAdminID()
	})
}

// ClearCreatedByAdminID clears the value of the "created_by_admin_id" field.
func (u *SharePolicyUpsertBulk) ClearCreatedByAdminID() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearCreatedByAdminID()
	})
}

// Exec executes the query.
func (u *SharePolicyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SharePolicyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharePolicyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharePolicyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
