// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/your-org/ai-gateway-platform/ent/predicate"
	"github.com/your-org/ai-gateway-platform/ent/sharepolicy"
)

// SharePolicyUpdate is the builder for updating SharePolicy entities.
type SharePolicyUpdate struct {
	config
	hooks    []Hook
	mutation *SharePolicyMutation
}

// Where appends a list predicates to the SharePolicyUpdate builder.
func (_u *SharePolicyUpdate) Where(ps ...predicate.SharePolicy) *SharePolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SharePolicyUpdate) SetUpdatedAt(v time.Time) *SharePolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SharePolicyUpdate) SetDeletedAt(v time.Time) *SharePolicyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableDeletedAt(v *time.Time) *SharePolicyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SharePolicyUpdate) ClearDeletedAt() *SharePolicyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *SharePolicyUpdate) SetScopeType(v string) *SharePolicyUpdate {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableScopeType(v *string) *SharePolicyUpdate {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *SharePolicyUpdate) SetScopeID(v int64) *SharePolicyUpdate {
	_u.mutation.ResetScopeID()
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableScopeID(v *int64) *SharePolicyUpdate {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// AddScopeID adds value to the "scope_id" field.
func (_u *SharePolicyUpdate) AddScopeID(v int64) *SharePolicyUpdate {
	_u.mutation.AddScopeID(v)
	return _u
}

// ClearScopeID clears the value of the "scope_id" field.
func (_u *SharePolicyUpdate) ClearScopeID() *SharePolicyUpdate {
	_u.mutation.ClearScopeID()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *SharePolicyUpdate) SetPlatform(v string) *SharePolicyUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillablePlatform(v *string) *SharePolicyUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// ClearPlatform clears the value of the "platform" field.
func (_u *SharePolicyUpdate) ClearPlatform() *SharePolicyUpdate {
	_u.mutation.ClearPlatform()
	return _u
}

// SetOwnerShareRatio sets the "owner_share_ratio" field.
func (_u *SharePolicyUpdate) SetOwnerShareRatio(v float64) *SharePolicyUpdate {
	_u.mutation.ResetOwnerShareRatio()
	_u.mutation.SetOwnerShareRatio(v)
	return _u
}

// SetNillableOwnerShareRatio sets the "owner_share_ratio" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableOwnerShareRatio(v *float64) *SharePolicyUpdate {
	if v != nil {
		_u.SetOwnerShareRatio(*v)
	}
	return _u
}

// AddOwnerShareRatio adds value to the "owner_share_ratio" field.
func (_u *SharePolicyUpdate) AddOwnerShareRatio(v float64) *SharePolicyUpdate {
	_u.mutation.AddOwnerShareRatio(v)
	return _u
}

// SetInviteShareRatio sets the "invite_share_ratio" field.
func (_u *SharePolicyUpdate) SetInviteShareRatio(v float64) *SharePolicyUpdate {
	_u.mutation.ResetInviteShareRatio()
	_u.mutation.SetInviteShareRatio(v)
	return _u
}

// SetNillableInviteShareRatio sets the "invite_share_ratio" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableInviteShareRatio(v *float64) *SharePolicyUpdate {
	if v != nil {
		_u.SetInviteShareRatio(*v)
	}
	return _u
}

// AddInviteShareRatio adds value to the "invite_share_ratio" field.
func (_u *SharePolicyUpdate) AddInviteShareRatio(v float64) *SharePolicyUpdate {
	_u.mutation.AddInviteShareRatio(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *SharePolicyUpdate) SetVersion(v int) *SharePolicyUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableVersion(v *int) *SharePolicyUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SharePolicyUpdate) AddVersion(v int) *SharePolicyUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SharePolicyUpdate) SetEnabled(v bool) *SharePolicyUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableEnabled(v *bool) *SharePolicyUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetEffectiveAt sets the "effective_at" field.
func (_u *SharePolicyUpdate) SetEffectiveAt(v time.Time) *SharePolicyUpdate {
	_u.mutation.SetEffectiveAt(v)
	return _u
}

// SetNillableEffectiveAt sets the "effective_at" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableEffectiveAt(v *time.Time) *SharePolicyUpdate {
	if v != nil {
		_u.SetEffectiveAt(*v)
	}
	return _u
}

// ClearEffectiveAt clears the value of the "effective_at" field.
func (_u *SharePolicyUpdate) ClearEffectiveAt() *SharePolicyUpdate {
	_u.mutation.ClearEffectiveAt()
	return _u
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (_u *SharePolicyUpdate) SetCreatedByAdminID(v int64) *SharePolicyUpdate {
	_u.mutation.ResetCreatedByAdminID()
	_u.mutation.SetCreatedByAdminID(v)
	return _u
}

// SetNillableCreatedByAdminID sets the "created_by_admin_id" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableCreatedByAdminID(v *int64) *SharePolicyUpdate {
	if v != nil {
		_u.SetCreatedByAdminID(*v)
	}
	return _u
}

// AddCreatedByAdminID adds value to the "created_by_admin_id" field.
func (_u *SharePolicyUpdate) AddCreatedByAdminID(v int64) *SharePolicyUpdate {
	_u.mutation.AddCreatedByAdminID(v)
	return _u
}

// ClearCreatedByAdminID clears the value of the "created_by_admin_id" field.
func (_u *SharePolicyUpdate) ClearCreatedByAdminID() *SharePolicyUpdate {
	_u.mutation.ClearCreatedByAdminID()
	return _u
}

// Mutation returns the SharePolicyMutation object of the builder.
func (_u *SharePolicyUpdate) Mutation() *SharePolicyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SharePolicyUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharePolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SharePolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharePolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SharePolicyUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if sharepolicy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharepolicy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharepolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharePolicyUpdate) check() error {
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := sharepolicy.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := sharepolicy.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerShareRatio(); ok {
		if err := sharepolicy.OwnerShareRatioValidator(v); err != nil {
			return &ValidationError{Name: "owner_share_ratio", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.owner_share_ratio": %w`, err)}
		}
	}
	return nil
}

func (_u *SharePolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharepolicy.Table, sharepolicy.Columns, sqlgraph.NewFieldSpec(sharepolicy.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sharepolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sharepolicy.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sharepolicy.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(sharepolicy.FieldScopeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(sharepolicy.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScopeID(); ok {
		_spec.AddField(sharepolicy.FieldScopeID, field.TypeInt64, value)
	}
	if _u.mutation.ScopeIDCleared() {
		_spec.ClearField(sharepolicy.FieldScopeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(sharepolicy.FieldPlatform, field.TypeString, value)
	}
	if _u.mutation.PlatformCleared() {
		_spec.ClearField(sharepolicy.FieldPlatform, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerShareRatio(); ok {
		_spec.SetField(sharepolicy.FieldOwnerShareRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOwnerShareRatio(); ok {
		_spec.AddField(sharepolicy.FieldOwnerShareRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InviteShareRatio(); ok {
		_spec.SetField(sharepolicy.FieldInviteShareRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInviteShareRatio(); ok {
		_spec.AddField(sharepolicy.FieldInviteShareRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(sharepolicy.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(sharepolicy.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(sharepolicy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EffectiveAt(); ok {
		_spec.SetField(sharepolicy.FieldEffectiveAt, field.TypeTime, value)
	}
	if _u.mutation.EffectiveAtCleared() {
		_spec.ClearField(sharepolicy.FieldEffectiveAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedByAdminID(); ok {
		_spec.SetField(sharepolicy.FieldCreatedByAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByAdminID(); ok {
		_spec.AddField(sharepolicy.FieldCreatedByAdminID, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByAdminIDCleared() {
		_spec.ClearField(sharepolicy.FieldCreatedByAdminID, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharepolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SharePolicyUpdateOne is the builder for updating a single SharePolicy entity.
type SharePolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SharePolicyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SharePolicyUpdateOne) SetUpdatedAt(v time.Time) *SharePolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SharePolicyUpdateOne) SetDeletedAt(v time.Time) *SharePolicyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableDeletedAt(v *time.Time) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SharePolicyUpdateOne) ClearDeletedAt() *SharePolicyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *SharePolicyUpdateOne) SetScopeType(v string) *SharePolicyUpdateOne {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableScopeType(v *string) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *SharePolicyUpdateOne) SetScopeID(v int64) *SharePolicyUpdateOne {
	_u.mutation.ResetScopeID()
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableScopeID(v *int64) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// AddScopeID adds value to the "scope_id" field.
func (_u *SharePolicyUpdateOne) AddScopeID(v int64) *SharePolicyUpdateOne {
	_u.mutation.AddScopeID(v)
	return _u
}

// ClearScopeID clears the value of the "scope_id" field.
func (_u *SharePolicyUpdateOne) ClearScopeID() *SharePolicyUpdateOne {
	_u.mutation.ClearScopeID()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *SharePolicyUpdateOne) SetPlatform(v string) *SharePolicyUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillablePlatform(v *string) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// ClearPlatform clears the value of the "platform" field.
func (_u *SharePolicyUpdateOne) ClearPlatform() *SharePolicyUpdateOne {
	_u.mutation.ClearPlatform()
	return _u
}

// SetOwnerShareRatio sets the "owner_share_ratio" field.
func (_u *SharePolicyUpdateOne) SetOwnerShareRatio(v float64) *SharePolicyUpdateOne {
	_u.mutation.ResetOwnerShareRatio()
	_u.mutation.SetOwnerShareRatio(v)
	return _u
}

// SetNillableOwnerShareRatio sets the "owner_share_ratio" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableOwnerShareRatio(v *float64) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetOwnerShareRatio(*v)
	}
	return _u
}

// AddOwnerShareRatio adds value to the "owner_share_ratio" field.
func (_u *SharePolicyUpdateOne) AddOwnerShareRatio(v float64) *SharePolicyUpdateOne {
	_u.mutation.AddOwnerShareRatio(v)
	return _u
}

// SetInviteShareRatio sets the "invite_share_ratio" field.
func (_u *SharePolicyUpdateOne) SetInviteShareRatio(v float64) *SharePolicyUpdateOne {
	_u.mutation.ResetInviteShareRatio()
	_u.mutation.SetInviteShareRatio(v)
	return _u
}

// SetNillableInviteShareRatio sets the "invite_share_ratio" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableInviteShareRatio(v *float64) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetInviteShareRatio(*v)
	}
	return _u
}

// AddInviteShareRatio adds value to the "invite_share_ratio" field.
func (_u *SharePolicyUpdateOne) AddInviteShareRatio(v float64) *SharePolicyUpdateOne {
	_u.mutation.AddInviteShareRatio(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *SharePolicyUpdateOne) SetVersion(v int) *SharePolicyUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableVersion(v *int) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SharePolicyUpdateOne) AddVersion(v int) *SharePolicyUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SharePolicyUpdateOne) SetEnabled(v bool) *SharePolicyUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableEnabled(v *bool) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetEffectiveAt sets the "effective_at" field.
func (_u *SharePolicyUpdateOne) SetEffectiveAt(v time.Time) *SharePolicyUpdateOne {
	_u.mutation.SetEffectiveAt(v)
	return _u
}

// SetNillableEffectiveAt sets the "effective_at" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableEffectiveAt(v *time.Time) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetEffectiveAt(*v)
	}
	return _u
}

// ClearEffectiveAt clears the value of the "effective_at" field.
func (_u *SharePolicyUpdateOne) ClearEffectiveAt() *SharePolicyUpdateOne {
	_u.mutation.ClearEffectiveAt()
	return _u
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (_u *SharePolicyUpdateOne) SetCreatedByAdminID(v int64) *SharePolicyUpdateOne {
	_u.mutation.ResetCreatedByAdminID()
	_u.mutation.SetCreatedByAdminID(v)
	return _u
}

// SetNillableCreatedByAdminID sets the "created_by_admin_id" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableCreatedByAdminID(v *int64) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetCreatedByAdminID(*v)
	}
	return _u
}

// AddCreatedByAdminID adds value to the "created_by_admin_id" field.
func (_u *SharePolicyUpdateOne) AddCreatedByAdminID(v int64) *SharePolicyUpdateOne {
	_u.mutation.AddCreatedByAdminID(v)
	return _u
}

// ClearCreatedByAdminID clears the value of the "created_by_admin_id" field.
func (_u *SharePolicyUpdateOne) ClearCreatedByAdminID() *SharePolicyUpdateOne {
	_u.mutation.ClearCreatedByAdminID()
	return _u
}

// Mutation returns the SharePolicyMutation object of the builder.
func (_u *SharePolicyUpdateOne) Mutation() *SharePolicyMutation {
	return _u.mutation
}

// Where appends a list predicates to the SharePolicyUpdate builder.
func (_u *SharePolicyUpdateOne) Where(ps ...predicate.SharePolicy) *SharePolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SharePolicyUpdateOne) Select(field string, fields ...string) *SharePolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SharePolicy entity.
func (_u *SharePolicyUpdateOne) Save(ctx context.Context) (*SharePolicy, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharePolicyUpdateOne) SaveX(ctx context.Context) *SharePolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SharePolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharePolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SharePolicyUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if sharepolicy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharepolicy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharepolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharePolicyUpdateOne) check() error {
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := sharepolicy.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := sharepolicy.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerShareRatio(); ok {
		if err := sharepolicy.OwnerShareRatioValidator(v); err != nil {
			return &ValidationError{Name: "owner_share_ratio", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.owner_share_ratio": %w`, err)}
		}
	}
	return nil
}

func (_u *SharePolicyUpdateOne) sqlSave(ctx context.Context) (_node *SharePolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharepolicy.Table, sharepolicy.Columns, sqlgraph.NewFieldSpec(sharepolicy.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SharePolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharepolicy.FieldID)
		for _, f := range fields {
			if !sharepolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sharepolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sharepolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sharepolicy.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sharepolicy.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(sharepolicy.FieldScopeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(sharepolicy.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScopeID(); ok {
		_spec.AddField(sharepolicy.FieldScopeID, field.TypeInt64, value)
	}
	if _u.mutation.ScopeIDCleared() {
		_spec.ClearField(sharepolicy.FieldScopeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(sharepolicy.FieldPlatform, field.TypeString, value)
	}
	if _u.mutation.PlatformCleared() {
		_spec.ClearField(sharepolicy.FieldPlatform, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerShareRatio(); ok {
		_spec.SetField(sharepolicy.FieldOwnerShareRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOwnerShareRatio(); ok {
		_spec.AddField(sharepolicy.FieldOwnerShareRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InviteShareRatio(); ok {
		_spec.SetField(sharepolicy.FieldInviteShareRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInviteShareRatio(); ok {
		_spec.AddField(sharepolicy.FieldInviteShareRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(sharepolicy.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(sharepolicy.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(sharepolicy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EffectiveAt(); ok {
		_spec.SetField(sharepolicy.FieldEffectiveAt, field.TypeTime, value)
	}
	if _u.mutation.EffectiveAtCleared() {
		_spec.ClearField(sharepolicy.FieldEffectiveAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedByAdminID(); ok {
		_spec.SetField(sharepolicy.FieldCreatedByAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByAdminID(); ok {
		_spec.AddField(sharepolicy.FieldCreatedByAdminID, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByAdminIDCleared() {
		_spec.ClearField(sharepolicy.FieldCreatedByAdminID, field.TypeInt64)
	}
	_node = &SharePolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharepolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
