// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/your-org/ai-gateway-platform/ent/predicate"
	"github.com/your-org/ai-gateway-platform/ent/withdrawal"
)

// WithdrawalUpdate is the builder for updating Withdrawal entities.
type WithdrawalUpdate struct {
	config
	hooks    []Hook
	mutation *WithdrawalMutation
}

// Where appends a list predicates to the WithdrawalUpdate builder.
func (_u *WithdrawalUpdate) Where(ps ...predicate.Withdrawal) *WithdrawalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WithdrawalUpdate) SetUpdatedAt(v time.Time) *WithdrawalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *WithdrawalUpdate) SetOwnerUserID(v int64) *WithdrawalUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *WithdrawalUpdate) SetNillableOwnerUserID(v *int64) *WithdrawalUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *WithdrawalUpdate) AddOwnerUserID(v int64) *WithdrawalUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *WithdrawalUpdate) SetAmount(v float64) *WithdrawalUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *WithdrawalUpdate) SetNillableAmount(v *float64) *WithdrawalUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *WithdrawalUpdate) AddAmount(v float64) *WithdrawalUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetFeeAmount sets the "fee_amount" field.
func (_u *WithdrawalUpdate) SetFeeAmount(v float64) *WithdrawalUpdate {
	_u.mutation.ResetFeeAmount()
	_u.mutation.SetFeeAmount(v)
	return _u
}

// SetNillableFeeAmount sets the "fee_amount" field if the given value is not nil.
func (_u *WithdrawalUpdate) SetNillableFeeAmount(v *float64) *WithdrawalUpdate {
	if v != nil {
		_u.SetFeeAmount(*v)
	}
	return _u
}

// AddFeeAmount adds value to the "fee_amount" field.
func (_u *WithdrawalUpdate) AddFeeAmount(v float64) *WithdrawalUpdate {
	_u.mutation.AddFeeAmount(v)
	return _u
}

// SetTotalDeducted sets the "total_deducted" field.
func (_u *WithdrawalUpdate) SetTotalDeducted(v float64) *WithdrawalUpdate {
	_u.mutation.ResetTotalDeducted()
	_u.mutation.SetTotalDeducted(v)
	return _u
}

// SetNillableTotalDeducted sets the "total_deducted" field if the given value is not nil.
func (_u *WithdrawalUpdate) SetNillableTotalDeducted(v *float64) *WithdrawalUpdate {
	if v != nil {
		_u.SetTotalDeducted(*v)
	}
	return _u
}

// AddTotalDeducted adds value to the "total_deducted" field.
func (_u *WithdrawalUpdate) AddTotalDeducted(v float64) *WithdrawalUpdate {
	_u.mutation.AddTotalDeducted(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *WithdrawalUpdate) SetBalanceBefore(v float64) *WithdrawalUpdate {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *WithdrawalUpdate) SetNillableBalanceBefore(v *float64) *WithdrawalUpdate {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *WithdrawalUpdate) AddBalanceBefore(v float64) *WithdrawalUpdate {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *WithdrawalUpdate) SetBalanceAfter(v float64) *WithdrawalUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *WithdrawalUpdate) SetNillableBalanceAfter(v *float64) *WithdrawalUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *WithdrawalUpdate) AddBalanceAfter(v float64) *WithdrawalUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *WithdrawalUpdate) SetPaymentMethod(v string) *WithdrawalUpdate {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *WithdrawalUpdate) SetNillablePaymentMethod(v *string) *WithdrawalUpdate {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetPaymentAccount sets the "payment_account" field.
func (_u *WithdrawalUpdate) SetPaymentAccount(v string) *WithdrawalUpdate {
	_u.mutation.SetPaymentAccount(v)
	return _u
}

// SetNillablePaymentAccount sets the "payment_account" field if the given value is not nil.
func (_u *WithdrawalUpdate) SetNillablePaymentAccount(v *string) *WithdrawalUpdate {
	if v != nil {
		_u.SetPaymentAccount(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WithdrawalUpdate) SetStatus(v string) *WithdrawalUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WithdrawalUpdate) SetNillableStatus(v *string) *WithdrawalUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProcessedByUserID sets the "processed_by_user_id" field.
func (_u *WithdrawalUpdate) SetProcessedByUserID(v int64) *WithdrawalUpdate {
	_u.mutation.ResetProcessedByUserID()
	_u.mutation.SetProcessedByUserID(v)
	return _u
}

// SetNillableProcessedByUserID sets the "processed_by_user_id" field if the given value is not nil.
func (_u *WithdrawalUpdate) SetNillableProcessedByUserID(v *int64) *WithdrawalUpdate {
	if v != nil {
		_u.SetProcessedByUserID(*v)
	}
	return _u
}

// AddProcessedByUserID adds value to the "processed_by_user_id" field.
func (_u *WithdrawalUpdate) AddProcessedByUserID(v int64) *WithdrawalUpdate {
	_u.mutation.AddProcessedByUserID(v)
	return _u
}

// ClearProcessedByUserID clears the value of the "processed_by_user_id" field.
func (_u *WithdrawalUpdate) ClearProcessedByUserID() *WithdrawalUpdate {
	_u.mutation.ClearProcessedByUserID()
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *WithdrawalUpdate) SetProcessedAt(v time.Time) *WithdrawalUpdate {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *WithdrawalUpdate) SetNillableProcessedAt(v *time.Time) *WithdrawalUpdate {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *WithdrawalUpdate) ClearProcessedAt() *WithdrawalUpdate {
	_u.mutation.ClearProcessedAt()
	return _u
}

// Mutation returns the WithdrawalMutation object of the builder.
func (_u *WithdrawalUpdate) Mutation() *WithdrawalMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WithdrawalUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WithdrawalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WithdrawalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WithdrawalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WithdrawalUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := withdrawal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WithdrawalUpdate) check() error {
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := withdrawal.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "Withdrawal.payment_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentAccount(); ok {
		if err := withdrawal.PaymentAccountValidator(v); err != nil {
			return &ValidationError{Name: "payment_account", err: fmt.Errorf(`ent: validator failed for field "Withdrawal.payment_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := withdrawal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Withdrawal.status": %w`, err)}
		}
	}
	return nil
}

func (_u *WithdrawalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(withdrawal.Table, withdrawal.Columns, sqlgraph.NewFieldSpec(withdrawal.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(withdrawal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(withdrawal.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(withdrawal.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(withdrawal.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(withdrawal.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeAmount(); ok {
		_spec.SetField(withdrawal.FieldFeeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeAmount(); ok {
		_spec.AddField(withdrawal.FieldFeeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalDeducted(); ok {
		_spec.SetField(withdrawal.FieldTotalDeducted, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalDeducted(); ok {
		_spec.AddField(withdrawal.FieldTotalDeducted, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(withdrawal.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(withdrawal.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(withdrawal.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(withdrawal.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(withdrawal.FieldPaymentMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentAccount(); ok {
		_spec.SetField(withdrawal.FieldPaymentAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(withdrawal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessedByUserID(); ok {
		_spec.SetField(withdrawal.FieldProcessedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProcessedByUserID(); ok {
		_spec.AddField(withdrawal.FieldProcessedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.ProcessedByUserIDCleared() {
		_spec.ClearField(withdrawal.FieldProcessedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(withdrawal.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(withdrawal.FieldProcessedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{withdrawal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WithdrawalUpdateOne is the builder for updating a single Withdrawal entity.
type WithdrawalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WithdrawalMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WithdrawalUpdateOne) SetUpdatedAt(v time.Time) *WithdrawalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *WithdrawalUpdateOne) SetOwnerUserID(v int64) *WithdrawalUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *WithdrawalUpdateOne) SetNillableOwnerUserID(v *int64) *WithdrawalUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *WithdrawalUpdateOne) AddOwnerUserID(v int64) *WithdrawalUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *WithdrawalUpdateOne) SetAmount(v float64) *WithdrawalUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *WithdrawalUpdateOne) SetNillableAmount(v *float64) *WithdrawalUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *WithdrawalUpdateOne) AddAmount(v float64) *WithdrawalUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetFeeAmount sets the "fee_amount" field.
func (_u *WithdrawalUpdateOne) SetFeeAmount(v float64) *WithdrawalUpdateOne {
	_u.mutation.ResetFeeAmount()
	_u.mutation.SetFeeAmount(v)
	return _u
}

// SetNillableFeeAmount sets the "fee_amount" field if the given value is not nil.
func (_u *WithdrawalUpdateOne) SetNillableFeeAmount(v *float64) *WithdrawalUpdateOne {
	if v != nil {
		_u.SetFeeAmount(*v)
	}
	return _u
}

// AddFeeAmount adds value to the "fee_amount" field.
func (_u *WithdrawalUpdateOne) AddFeeAmount(v float64) *WithdrawalUpdateOne {
	_u.mutation.AddFeeAmount(v)
	return _u
}

// SetTotalDeducted sets the "total_deducted" field.
func (_u *WithdrawalUpdateOne) SetTotalDeducted(v float64) *WithdrawalUpdateOne {
	_u.mutation.ResetTotalDeducted()
	_u.mutation.SetTotalDeducted(v)
	return _u
}

// SetNillableTotalDeducted sets the "total_deducted" field if the given value is not nil.
func (_u *WithdrawalUpdateOne) SetNillableTotalDeducted(v *float64) *WithdrawalUpdateOne {
	if v != nil {
		_u.SetTotalDeducted(*v)
	}
	return _u
}

// AddTotalDeducted adds value to the "total_deducted" field.
func (_u *WithdrawalUpdateOne) AddTotalDeducted(v float64) *WithdrawalUpdateOne {
	_u.mutation.AddTotalDeducted(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *WithdrawalUpdateOne) SetBalanceBefore(v float64) *WithdrawalUpdateOne {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *WithdrawalUpdateOne) SetNillableBalanceBefore(v *float64) *WithdrawalUpdateOne {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *WithdrawalUpdateOne) AddBalanceBefore(v float64) *WithdrawalUpdateOne {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *WithdrawalUpdateOne) SetBalanceAfter(v float64) *WithdrawalUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *WithdrawalUpdateOne) SetNillableBalanceAfter(v *float64) *WithdrawalUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *WithdrawalUpdateOne) AddBalanceAfter(v float64) *WithdrawalUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *WithdrawalUpdateOne) SetPaymentMethod(v string) *WithdrawalUpdateOne {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *WithdrawalUpdateOne) SetNillablePaymentMethod(v *string) *WithdrawalUpdateOne {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetPaymentAccount sets the "payment_account" field.
func (_u *WithdrawalUpdateOne) SetPaymentAccount(v string) *WithdrawalUpdateOne {
	_u.mutation.SetPaymentAccount(v)
	return _u
}

// SetNillablePaymentAccount sets the "payment_account" field if the given value is not nil.
func (_u *WithdrawalUpdateOne) SetNillablePaymentAccount(v *string) *WithdrawalUpdateOne {
	if v != nil {
		_u.SetPaymentAccount(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WithdrawalUpdateOne) SetStatus(v string) *WithdrawalUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WithdrawalUpdateOne) SetNillableStatus(v *string) *WithdrawalUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProcessedByUserID sets the "processed_by_user_id" field.
func (_u *WithdrawalUpdateOne) SetProcessedByUserID(v int64) *WithdrawalUpdateOne {
	_u.mutation.ResetProcessedByUserID()
	_u.mutation.SetProcessedByUserID(v)
	return _u
}

// SetNillableProcessedByUserID sets the "processed_by_user_id" field if the given value is not nil.
func (_u *WithdrawalUpdateOne) SetNillableProcessedByUserID(v *int64) *WithdrawalUpdateOne {
	if v != nil {
		_u.SetProcessedByUserID(*v)
	}
	return _u
}

// AddProcessedByUserID adds value to the "processed_by_user_id" field.
func (_u *WithdrawalUpdateOne) AddProcessedByUserID(v int64) *WithdrawalUpdateOne {
	_u.mutation.AddProcessedByUserID(v)
	return _u
}

// ClearProcessedByUserID clears the value of the "processed_by_user_id" field.
func (_u *WithdrawalUpdateOne) ClearProcessedByUserID() *WithdrawalUpdateOne {
	_u.mutation.ClearProcessedByUserID()
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *WithdrawalUpdateOne) SetProcessedAt(v time.Time) *WithdrawalUpdateOne {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *WithdrawalUpdateOne) SetNillableProcessedAt(v *time.Time) *WithdrawalUpdateOne {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *WithdrawalUpdateOne) ClearProcessedAt() *WithdrawalUpdateOne {
	_u.mutation.ClearProcessedAt()
	return _u
}

// Mutation returns the WithdrawalMutation object of the builder.
func (_u *WithdrawalUpdateOne) Mutation() *WithdrawalMutation {
	return _u.mutation
}

// Where appends a list predicates to the WithdrawalUpdate builder.
func (_u *WithdrawalUpdateOne) Where(ps ...predicate.Withdrawal) *WithdrawalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WithdrawalUpdateOne) Select(field string, fields ...string) *WithdrawalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Withdrawal entity.
func (_u *WithdrawalUpdateOne) Save(ctx context.Context) (*Withdrawal, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WithdrawalUpdateOne) SaveX(ctx context.Context) *Withdrawal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WithdrawalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WithdrawalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WithdrawalUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := withdrawal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WithdrawalUpdateOne) check() error {
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := withdrawal.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "Withdrawal.payment_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentAccount(); ok {
		if err := withdrawal.PaymentAccountValidator(v); err != nil {
			return &ValidationError{Name: "payment_account", err: fmt.Errorf(`ent: validator failed for field "Withdrawal.payment_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := withdrawal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Withdrawal.status": %w`, err)}
		}
	}
	return nil
}

func (_u *WithdrawalUpdateOne) sqlSave(ctx context.Context) (_node *Withdrawal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(withdrawal.Table, withdrawal.Columns, sqlgraph.NewFieldSpec(withdrawal.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Withdrawal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, withdrawal.FieldID)
		for _, f := range fields {
			if !withdrawal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != withdrawal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(withdrawal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(withdrawal.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(withdrawal.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(withdrawal.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(withdrawal.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeAmount(); ok {
		_spec.SetField(withdrawal.FieldFeeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeAmount(); ok {
		_spec.AddField(withdrawal.FieldFeeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalDeducted(); ok {
		_spec.SetField(withdrawal.FieldTotalDeducted, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalDeducted(); ok {
		_spec.AddField(withdrawal.FieldTotalDeducted, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(withdrawal.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(withdrawal.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(withdrawal.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(withdrawal.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(withdrawal.FieldPaymentMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentAccount(); ok {
		_spec.SetField(withdrawal.FieldPaymentAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(withdrawal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessedByUserID(); ok {
		_spec.SetField(withdrawal.FieldProcessedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProcessedByUserID(); ok {
		_spec.AddField(withdrawal.FieldProcessedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.ProcessedByUserIDCleared() {
		_spec.ClearField(withdrawal.FieldProcessedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(withdrawal.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(withdrawal.FieldProcessedAt, field.TypeTime)
	}
	_node = &Withdrawal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{withdrawal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
