// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/your-org/ai-gateway-platform/ent/withdrawal"
)

// Withdrawal is the model entity for the Withdrawal schema.
type Withdrawal struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// FeeAmount holds the value of the "fee_amount" field.
	FeeAmount float64 `json:"fee_amount,omitempty"`
	// TotalDeducted holds the value of the "total_deducted" field.
	TotalDeducted float64 `json:"total_deducted,omitempty"`
	// BalanceBefore holds the value of the "balance_before" field.
	BalanceBefore float64 `json:"balance_before,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter float64 `json:"balance_after,omitempty"`
	// PaymentMethod holds the value of the "payment_method" field.
	PaymentMethod string `json:"payment_method,omitempty"`
	// PaymentAccount holds the value of the "payment_account" field.
	PaymentAccount string `json:"payment_account,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ProcessedByUserID holds the value of the "processed_by_user_id" field.
	ProcessedByUserID *int64 `json:"processed_by_user_id,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt  *time.Time `json:"processed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Withdrawal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case withdrawal.FieldAmount, withdrawal.FieldFeeAmount, withdrawal.FieldTotalDeducted, withdrawal.FieldBalanceBefore, withdrawal.FieldBalanceAfter:
			values[i] = new(sql.NullFloat64)
		case withdrawal.FieldID, withdrawal.FieldOwnerUserID, withdrawal.FieldProcessedByUserID:
			values[i] = new(sql.NullInt64)
		case withdrawal.FieldPaymentMethod, withdrawal.FieldPaymentAccount, withdrawal.FieldStatus:
			values[i] = new(sql.NullString)
		case withdrawal.FieldCreatedAt, withdrawal.FieldUpdatedAt, withdrawal.FieldProcessedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Withdrawal fields.
func (_m *Withdrawal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case withdrawal.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case withdrawal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case withdrawal.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case withdrawal.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case withdrawal.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case withdrawal.FieldFeeAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_amount", values[i])
			} else if value.Valid {
				_m.FeeAmount = value.Float64
			}
		case withdrawal.FieldTotalDeducted:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_deducted", values[i])
			} else if value.Valid {
				_m.TotalDeducted = value.Float64
			}
		case withdrawal.FieldBalanceBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_before", values[i])
			} else if value.Valid {
				_m.BalanceBefore = value.Float64
			}
		case withdrawal.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = value.Float64
			}
		case withdrawal.FieldPaymentMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method", values[i])
			} else if value.Valid {
				_m.PaymentMethod = value.String
			}
		case withdrawal.FieldPaymentAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_account", values[i])
			} else if value.Valid {
				_m.PaymentAccount = value.String
			}
		case withdrawal.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case withdrawal.FieldProcessedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field processed_by_user_id", values[i])
			} else if value.Valid {
				_m.ProcessedByUserID = new(int64)
				*_m.ProcessedByUserID = value.Int64
			}
		case withdrawal.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = new(time.Time)
				*_m.ProcessedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Withdrawal.
// This includes values selected through modifiers, order, etc.
func (_m *Withdrawal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Withdrawal.
// Note that you need to call Withdrawal.Unwrap() before calling this method if this Withdrawal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Withdrawal) Update() *WithdrawalUpdateOne {
	return NewWithdrawalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Withdrawal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Withdrawal) Unwrap() *Withdrawal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Withdrawal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Withdrawal) String() string {
	var builder strings.Builder
	builder.WriteString("Withdrawal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("fee_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeeAmount))
	builder.WriteString(", ")
	builder.WriteString("total_deducted=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalDeducted))
	builder.WriteString(", ")
	builder.WriteString("balance_before=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceBefore))
	builder.WriteString(", ")
	builder.WriteString("balance_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfter))
	builder.WriteString(", ")
	builder.WriteString("payment_method=")
	builder.WriteString(_m.PaymentMethod)
	builder.WriteString(", ")
	builder.WriteString("payment_account=")
	builder.WriteString(_m.PaymentAccount)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ProcessedByUserID; v != nil {
		builder.WriteString("processed_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Withdrawals is a parsable slice of Withdrawal.
type Withdrawals []*Withdrawal
