// Code generated by ent, DO NOT EDIT.

package settlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the settlement type in the database.
	Label = "settlement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldSettlementNo holds the string denoting the settlement_no field in the database.
	FieldSettlementNo = "settlement_no"
	// FieldPeriodStart holds the string denoting the period_start field in the database.
	FieldPeriodStart = "period_start"
	// FieldPeriodEnd holds the string denoting the period_end field in the database.
	FieldPeriodEnd = "period_end"
	// FieldGrossAmount holds the string denoting the gross_amount field in the database.
	FieldGrossAmount = "gross_amount"
	// FieldFeeAmount holds the string denoting the fee_amount field in the database.
	FieldFeeAmount = "fee_amount"
	// FieldNetAmount holds the string denoting the net_amount field in the database.
	FieldNetAmount = "net_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// Table holds the table name of the settlement in the database.
	Table = "settlements"
)

// Columns holds all SQL columns for settlement fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOwnerUserID,
	FieldSettlementNo,
	FieldPeriodStart,
	FieldPeriodEnd,
	FieldGrossAmount,
	FieldFeeAmount,
	FieldNetAmount,
	FieldStatus,
	FieldSettledAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// SettlementNoValidator is a validator for the "settlement_no" field. It is called by the builders before save.
	SettlementNoValidator func(string) error
	// DefaultGrossAmount holds the default value on creation for the "gross_amount" field.
	DefaultGrossAmount float64
	// DefaultFeeAmount holds the default value on creation for the "fee_amount" field.
	DefaultFeeAmount float64
	// DefaultNetAmount holds the default value on creation for the "net_amount" field.
	DefaultNetAmount float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the Settlement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// BySettlementNo orders the results by the settlement_no field.
func BySettlementNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementNo, opts...).ToFunc()
}

// ByPeriodStart orders the results by the period_start field.
func ByPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodStart, opts...).ToFunc()
}

// ByPeriodEnd orders the results by the period_end field.
func ByPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodEnd, opts...).ToFunc()
}

// ByGrossAmount orders the results by the gross_amount field.
func ByGrossAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrossAmount, opts...).ToFunc()
}

// ByFeeAmount orders the results by the fee_amount field.
func ByFeeAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeAmount, opts...).ToFunc()
}

// ByNetAmount orders the results by the net_amount field.
func ByNetAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}
