// Code generated by ent, DO NOT EDIT.

package settlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/your-org/ai-gateway-platform/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldOwnerUserID, v))
}

// SettlementNo applies equality check predicate on the "settlement_no" field. It's identical to SettlementNoEQ.
func SettlementNo(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldSettlementNo, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodEnd applies equality check predicate on the "period_end" field. It's identical to PeriodEndEQ.
func PeriodEnd(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldPeriodEnd, v))
}

// GrossAmount applies equality check predicate on the "gross_amount" field. It's identical to GrossAmountEQ.
func GrossAmount(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldGrossAmount, v))
}

// FeeAmount applies equality check predicate on the "fee_amount" field. It's identical to FeeAmountEQ.
func FeeAmount(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldFeeAmount, v))
}

// NetAmount applies equality check predicate on the "net_amount" field. It's identical to NetAmountEQ.
func NetAmount(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldNetAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldStatus, v))
}

// SettledAt applies equality check predicate on the "settled_at" field. It's identical to SettledAtEQ.
func SettledAt(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldSettledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldUpdatedAt, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldOwnerUserID, v))
}

// SettlementNoEQ applies the EQ predicate on the "settlement_no" field.
func SettlementNoEQ(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldSettlementNo, v))
}

// SettlementNoNEQ applies the NEQ predicate on the "settlement_no" field.
func SettlementNoNEQ(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldSettlementNo, v))
}

// SettlementNoIn applies the In predicate on the "settlement_no" field.
func SettlementNoIn(vs ...string) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldSettlementNo, vs...))
}

// SettlementNoNotIn applies the NotIn predicate on the "settlement_no" field.
func SettlementNoNotIn(vs ...string) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldSettlementNo, vs...))
}

// SettlementNoGT applies the GT predicate on the "settlement_no" field.
func SettlementNoGT(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldSettlementNo, v))
}

// SettlementNoGTE applies the GTE predicate on the "settlement_no" field.
func SettlementNoGTE(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldSettlementNo, v))
}

// SettlementNoLT applies the LT predicate on the "settlement_no" field.
func SettlementNoLT(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldSettlementNo, v))
}

// SettlementNoLTE applies the LTE predicate on the "settlement_no" field.
func SettlementNoLTE(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldSettlementNo, v))
}

// SettlementNoContains applies the Contains predicate on the "settlement_no" field.
func SettlementNoContains(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldContains(FieldSettlementNo, v))
}

// SettlementNoHasPrefix applies the HasPrefix predicate on the "settlement_no" field.
func SettlementNoHasPrefix(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldHasPrefix(FieldSettlementNo, v))
}

// SettlementNoHasSuffix applies the HasSuffix predicate on the "settlement_no" field.
func SettlementNoHasSuffix(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldHasSuffix(FieldSettlementNo, v))
}

// SettlementNoEqualFold applies the EqualFold predicate on the "settlement_no" field.
func SettlementNoEqualFold(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEqualFold(FieldSettlementNo, v))
}

// SettlementNoContainsFold applies the ContainsFold predicate on the "settlement_no" field.
func SettlementNoContainsFold(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldContainsFold(FieldSettlementNo, v))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodEndEQ applies the EQ predicate on the "period_end" field.
func PeriodEndEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldPeriodEnd, v))
}

// PeriodEndNEQ applies the NEQ predicate on the "period_end" field.
func PeriodEndNEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldPeriodEnd, v))
}

// PeriodEndIn applies the In predicate on the "period_end" field.
func PeriodEndIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldPeriodEnd, vs...))
}

// PeriodEndNotIn applies the NotIn predicate on the "period_end" field.
func PeriodEndNotIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldPeriodEnd, vs...))
}

// PeriodEndGT applies the GT predicate on the "period_end" field.
func PeriodEndGT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldPeriodEnd, v))
}

// PeriodEndGTE applies the GTE predicate on the "period_end" field.
func PeriodEndGTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldPeriodEnd, v))
}

// PeriodEndLT applies the LT predicate on the "period_end" field.
func PeriodEndLT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldPeriodEnd, v))
}

// PeriodEndLTE applies the LTE predicate on the "period_end" field.
func PeriodEndLTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldPeriodEnd, v))
}

// GrossAmountEQ applies the EQ predicate on the "gross_amount" field.
func GrossAmountEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldGrossAmount, v))
}

// GrossAmountNEQ applies the NEQ predicate on the "gross_amount" field.
func GrossAmountNEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldGrossAmount, v))
}

// GrossAmountIn applies the In predicate on the "gross_amount" field.
func GrossAmountIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldGrossAmount, vs...))
}

// GrossAmountNotIn applies the NotIn predicate on the "gross_amount" field.
func GrossAmountNotIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldGrossAmount, vs...))
}

// GrossAmountGT applies the GT predicate on the "gross_amount" field.
func GrossAmountGT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldGrossAmount, v))
}

// GrossAmountGTE applies the GTE predicate on the "gross_amount" field.
func GrossAmountGTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldGrossAmount, v))
}

// GrossAmountLT applies the LT predicate on the "gross_amount" field.
func GrossAmountLT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldGrossAmount, v))
}

// GrossAmountLTE applies the LTE predicate on the "gross_amount" field.
func GrossAmountLTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldGrossAmount, v))
}

// FeeAmountEQ applies the EQ predicate on the "fee_amount" field.
func FeeAmountEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldFeeAmount, v))
}

// FeeAmountNEQ applies the NEQ predicate on the "fee_amount" field.
func FeeAmountNEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldFeeAmount, v))
}

// FeeAmountIn applies the In predicate on the "fee_amount" field.
func FeeAmountIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldFeeAmount, vs...))
}

// FeeAmountNotIn applies the NotIn predicate on the "fee_amount" field.
func FeeAmountNotIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldFeeAmount, vs...))
}

// FeeAmountGT applies the GT predicate on the "fee_amount" field.
func FeeAmountGT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldFeeAmount, v))
}

// FeeAmountGTE applies the GTE predicate on the "fee_amount" field.
func FeeAmountGTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldFeeAmount, v))
}

// FeeAmountLT applies the LT predicate on the "fee_amount" field.
func FeeAmountLT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldFeeAmount, v))
}

// FeeAmountLTE applies the LTE predicate on the "fee_amount" field.
func FeeAmountLTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldFeeAmount, v))
}

// NetAmountEQ applies the EQ predicate on the "net_amount" field.
func NetAmountEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldNetAmount, v))
}

// NetAmountNEQ applies the NEQ predicate on the "net_amount" field.
func NetAmountNEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldNetAmount, v))
}

// NetAmountIn applies the In predicate on the "net_amount" field.
func NetAmountIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldNetAmount, vs...))
}

// NetAmountNotIn applies the NotIn predicate on the "net_amount" field.
func NetAmountNotIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldNetAmount, vs...))
}

// NetAmountGT applies the GT predicate on the "net_amount" field.
func NetAmountGT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldNetAmount, v))
}

// NetAmountGTE applies the GTE predicate on the "net_amount" field.
func NetAmountGTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldNetAmount, v))
}

// NetAmountLT applies the LT predicate on the "net_amount" field.
func NetAmountLT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldNetAmount, v))
}

// NetAmountLTE applies the LTE predicate on the "net_amount" field.
func NetAmountLTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldNetAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldContainsFold(FieldStatus, v))
}

// SettledAtEQ applies the EQ predicate on the "settled_at" field.
func SettledAtEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldSettledAt, v))
}

// SettledAtNEQ applies the NEQ predicate on the "settled_at" field.
func SettledAtNEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldSettledAt, v))
}

// SettledAtIn applies the In predicate on the "settled_at" field.
func SettledAtIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldSettledAt, vs...))
}

// SettledAtNotIn applies the NotIn predicate on the "settled_at" field.
func SettledAtNotIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldSettledAt, vs...))
}

// SettledAtGT applies the GT predicate on the "settled_at" field.
func SettledAtGT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldSettledAt, v))
}

// SettledAtGTE applies the GTE predicate on the "settled_at" field.
func SettledAtGTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldSettledAt, v))
}

// SettledAtLT applies the LT predicate on the "settled_at" field.
func SettledAtLT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldSettledAt, v))
}

// SettledAtLTE applies the LTE predicate on the "settled_at" field.
func SettledAtLTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldSettledAt, v))
}

// SettledAtIsNil applies the IsNil predicate on the "settled_at" field.
func SettledAtIsNil() predicate.Settlement {
	return predicate.Settlement(sql.FieldIsNull(FieldSettledAt))
}

// SettledAtNotNil applies the NotNil predicate on the "settled_at" field.
func SettledAtNotNil() predicate.Settlement {
	return predicate.Settlement(sql.FieldNotNull(FieldSettledAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Settlement) predicate.Settlement {
	return predicate.Settlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Settlement) predicate.Settlement {
	return predicate.Settlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Settlement) predicate.Settlement {
	return predicate.Settlement(sql.NotPredicates(p))
}
