// Code generated by ent, DO NOT EDIT.

package sharepolicy

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sharepolicy type in the database.
	Label = "share_policy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldScopeType holds the string denoting the scope_type field in the database.
	FieldScopeType = "scope_type"
	// FieldScopeID holds the string denoting the scope_id field in the database.
	FieldScopeID = "scope_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldOwnerShareRatio holds the string denoting the owner_share_ratio field in the database.
	FieldOwnerShareRatio = "owner_share_ratio"
	// FieldInviteShareRatio holds the string denoting the invite_share_ratio field in the database.
	FieldInviteShareRatio = "invite_share_ratio"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldEffectiveAt holds the string denoting the effective_at field in the database.
	FieldEffectiveAt = "effective_at"
	// FieldCreatedByAdminID holds the string denoting the created_by_admin_id field in the database.
	FieldCreatedByAdminID = "created_by_admin_id"
	// Table holds the table name of the sharepolicy in the database.
	Table = "share_policies"
)

// Columns holds all SQL columns for sharepolicy fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldScopeType,
	FieldScopeID,
	FieldPlatform,
	FieldOwnerShareRatio,
	FieldInviteShareRatio,
	FieldVersion,
	FieldEnabled,
	FieldEffectiveAt,
	FieldCreatedByAdminID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/your-org/ai-gateway-platform/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ScopeTypeValidator is a validator for the "scope_type" field. It is called by the builders before save.
	ScopeTypeValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// OwnerShareRatioValidator is a validator for the "owner_share_ratio" field. It is called by the builders before save.
	OwnerShareRatioValidator func(float64) error
	// DefaultInviteShareRatio holds the default value on creation for the "invite_share_ratio" field.
	DefaultInviteShareRatio float64
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the SharePolicy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByScopeType orders the results by the scope_type field.
func ByScopeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeType, opts...).ToFunc()
}

// ByScopeID orders the results by the scope_id field.
func ByScopeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByOwnerShareRatio orders the results by the owner_share_ratio field.
func ByOwnerShareRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerShareRatio, opts...).ToFunc()
}

// ByInviteShareRatio orders the results by the invite_share_ratio field.
func ByInviteShareRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteShareRatio, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByEffectiveAt orders the results by the effective_at field.
func ByEffectiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveAt, opts...).ToFunc()
}

// ByCreatedByAdminID orders the results by the created_by_admin_id field.
func ByCreatedByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByAdminID, opts...).ToFunc()
}
