// Code generated by ent, DO NOT EDIT.

package sharepolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/your-org/ai-gateway-platform/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldDeletedAt, v))
}

// ScopeType applies equality check predicate on the "scope_type" field. It's identical to ScopeTypeEQ.
func ScopeType(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldScopeType, v))
}

// ScopeID applies equality check predicate on the "scope_id" field. It's identical to ScopeIDEQ.
func ScopeID(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldScopeID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldPlatform, v))
}

// OwnerShareRatio applies equality check predicate on the "owner_share_ratio" field. It's identical to OwnerShareRatioEQ.
func OwnerShareRatio(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldOwnerShareRatio, v))
}

// InviteShareRatio applies equality check predicate on the "invite_share_ratio" field. It's identical to InviteShareRatioEQ.
func InviteShareRatio(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldInviteShareRatio, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldVersion, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldEnabled, v))
}

// EffectiveAt applies equality check predicate on the "effective_at" field. It's identical to EffectiveAtEQ.
func EffectiveAt(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldEffectiveAt, v))
}

// CreatedByAdminID applies equality check predicate on the "created_by_admin_id" field. It's identical to CreatedByAdminIDEQ.
func CreatedByAdminID(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldCreatedByAdminID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotNull(FieldDeletedAt))
}

// ScopeTypeEQ applies the EQ predicate on the "scope_type" field.
func ScopeTypeEQ(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldScopeType, v))
}

// ScopeTypeNEQ applies the NEQ predicate on the "scope_type" field.
func ScopeTypeNEQ(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldScopeType, v))
}

// ScopeTypeIn applies the In predicate on the "scope_type" field.
func ScopeTypeIn(vs ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldScopeType, vs...))
}

// ScopeTypeNotIn applies the NotIn predicate on the "scope_type" field.
func ScopeTypeNotIn(vs ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldScopeType, vs...))
}

// ScopeTypeGT applies the GT predicate on the "scope_type" field.
func ScopeTypeGT(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldScopeType, v))
}

// ScopeTypeGTE applies the GTE predicate on the "scope_type" field.
func ScopeTypeGTE(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldScopeType, v))
}

// ScopeTypeLT applies the LT predicate on the "scope_type" field.
func ScopeTypeLT(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldScopeType, v))
}

// ScopeTypeLTE applies the LTE predicate on the "scope_type" field.
func ScopeTypeLTE(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldScopeType, v))
}

// ScopeTypeContains applies the Contains predicate on the "scope_type" field.
func ScopeTypeContains(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldContains(FieldScopeType, v))
}

// ScopeTypeHasPrefix applies the HasPrefix predicate on the "scope_type" field.
func ScopeTypeHasPrefix(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldHasPrefix(FieldScopeType, v))
}

// ScopeTypeHasSuffix applies the HasSuffix predicate on the "scope_type" field.
func ScopeTypeHasSuffix(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldHasSuffix(FieldScopeType, v))
}

// ScopeTypeEqualFold applies the EqualFold predicate on the "scope_type" field.
func ScopeTypeEqualFold(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEqualFold(FieldScopeType, v))
}

// ScopeTypeContainsFold applies the ContainsFold predicate on the "scope_type" field.
func ScopeTypeContainsFold(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldContainsFold(FieldScopeType, v))
}

// ScopeIDEQ applies the EQ predicate on the "scope_id" field.
func ScopeIDEQ(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldScopeID, v))
}

// ScopeIDNEQ applies the NEQ predicate on the "scope_id" field.
func ScopeIDNEQ(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldScopeID, v))
}

// ScopeIDIn applies the In predicate on the "scope_id" field.
func ScopeIDIn(vs ...int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldScopeID, vs...))
}

// ScopeIDNotIn applies the NotIn predicate on the "scope_id" field.
func ScopeIDNotIn(vs ...int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldScopeID, vs...))
}

// ScopeIDGT applies the GT predicate on the "scope_id" field.
func ScopeIDGT(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldScopeID, v))
}

// ScopeIDGTE applies the GTE predicate on the "scope_id" field.
func ScopeIDGTE(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldScopeID, v))
}

// ScopeIDLT applies the LT predicate on the "scope_id" field.
func ScopeIDLT(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldScopeID, v))
}

// ScopeIDLTE applies the LTE predicate on the "scope_id" field.
func ScopeIDLTE(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldScopeID, v))
}

// ScopeIDIsNil applies the IsNil predicate on the "scope_id" field.
func ScopeIDIsNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIsNull(FieldScopeID))
}

// ScopeIDNotNil applies the NotNil predicate on the "scope_id" field.
func ScopeIDNotNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotNull(FieldScopeID))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformIsNil applies the IsNil predicate on the "platform" field.
func PlatformIsNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIsNull(FieldPlatform))
}

// PlatformNotNil applies the NotNil predicate on the "platform" field.
func PlatformNotNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotNull(FieldPlatform))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldContainsFold(FieldPlatform, v))
}

// OwnerShareRatioEQ applies the EQ predicate on the "owner_share_ratio" field.
func OwnerShareRatioEQ(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldOwnerShareRatio, v))
}

// OwnerShareRatioNEQ applies the NEQ predicate on the "owner_share_ratio" field.
func OwnerShareRatioNEQ(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldOwnerShareRatio, v))
}

// OwnerShareRatioIn applies the In predicate on the "owner_share_ratio" field.
func OwnerShareRatioIn(vs ...float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldOwnerShareRatio, vs...))
}

// OwnerShareRatioNotIn applies the NotIn predicate on the "owner_share_ratio" field.
func OwnerShareRatioNotIn(vs ...float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldOwnerShareRatio, vs...))
}

// OwnerShareRatioGT applies the GT predicate on the "owner_share_ratio" field.
func OwnerShareRatioGT(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldOwnerShareRatio, v))
}

// OwnerShareRatioGTE applies the GTE predicate on the "owner_share_ratio" field.
func OwnerShareRatioGTE(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldOwnerShareRatio, v))
}

// OwnerShareRatioLT applies the LT predicate on the "owner_share_ratio" field.
func OwnerShareRatioLT(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldOwnerShareRatio, v))
}

// OwnerShareRatioLTE applies the LTE predicate on the "owner_share_ratio" field.
func OwnerShareRatioLTE(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldOwnerShareRatio, v))
}

// InviteShareRatioEQ applies the EQ predicate on the "invite_share_ratio" field.
func InviteShareRatioEQ(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldInviteShareRatio, v))
}

// InviteShareRatioNEQ applies the NEQ predicate on the "invite_share_ratio" field.
func InviteShareRatioNEQ(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldInviteShareRatio, v))
}

// InviteShareRatioIn applies the In predicate on the "invite_share_ratio" field.
func InviteShareRatioIn(vs ...float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldInviteShareRatio, vs...))
}

// InviteShareRatioNotIn applies the NotIn predicate on the "invite_share_ratio" field.
func InviteShareRatioNotIn(vs ...float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldInviteShareRatio, vs...))
}

// InviteShareRatioGT applies the GT predicate on the "invite_share_ratio" field.
func InviteShareRatioGT(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldInviteShareRatio, v))
}

// InviteShareRatioGTE applies the GTE predicate on the "invite_share_ratio" field.
func InviteShareRatioGTE(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldInviteShareRatio, v))
}

// InviteShareRatioLT applies the LT predicate on the "invite_share_ratio" field.
func InviteShareRatioLT(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldInviteShareRatio, v))
}

// InviteShareRatioLTE applies the LTE predicate on the "invite_share_ratio" field.
func InviteShareRatioLTE(v float64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldInviteShareRatio, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldVersion, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldEnabled, v))
}

// EffectiveAtEQ applies the EQ predicate on the "effective_at" field.
func EffectiveAtEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldEffectiveAt, v))
}

// EffectiveAtNEQ applies the NEQ predicate on the "effective_at" field.
func EffectiveAtNEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldEffectiveAt, v))
}

// EffectiveAtIn applies the In predicate on the "effective_at" field.
func EffectiveAtIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldEffectiveAt, vs...))
}

// EffectiveAtNotIn applies the NotIn predicate on the "effective_at" field.
func EffectiveAtNotIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldEffectiveAt, vs...))
}

// EffectiveAtGT applies the GT predicate on the "effective_at" field.
func EffectiveAtGT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldEffectiveAt, v))
}

// EffectiveAtGTE applies the GTE predicate on the "effective_at" field.
func EffectiveAtGTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldEffectiveAt, v))
}

// EffectiveAtLT applies the LT predicate on the "effective_at" field.
func EffectiveAtLT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldEffectiveAt, v))
}

// EffectiveAtLTE applies the LTE predicate on the "effective_at" field.
func EffectiveAtLTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldEffectiveAt, v))
}

// EffectiveAtIsNil applies the IsNil predicate on the "effective_at" field.
func EffectiveAtIsNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIsNull(FieldEffectiveAt))
}

// EffectiveAtNotNil applies the NotNil predicate on the "effective_at" field.
func EffectiveAtNotNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotNull(FieldEffectiveAt))
}

// CreatedByAdminIDEQ applies the EQ predicate on the "created_by_admin_id" field.
func CreatedByAdminIDEQ(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDNEQ applies the NEQ predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNEQ(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDIn applies the In predicate on the "created_by_admin_id" field.
func CreatedByAdminIDIn(vs ...int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldCreatedByAdminID, vs...))
}

// CreatedByAdminIDNotIn applies the NotIn predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNotIn(vs ...int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldCreatedByAdminID, vs...))
}

// CreatedByAdminIDGT applies the GT predicate on the "created_by_admin_id" field.
func CreatedByAdminIDGT(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDGTE applies the GTE predicate on the "created_by_admin_id" field.
func CreatedByAdminIDGTE(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDLT applies the LT predicate on the "created_by_admin_id" field.
func CreatedByAdminIDLT(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDLTE applies the LTE predicate on the "created_by_admin_id" field.
func CreatedByAdminIDLTE(v int64) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDIsNil applies the IsNil predicate on the "created_by_admin_id" field.
func CreatedByAdminIDIsNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIsNull(FieldCreatedByAdminID))
}

// CreatedByAdminIDNotNil applies the NotNil predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNotNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotNull(FieldCreatedByAdminID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SharePolicy) predicate.SharePolicy {
	return predicate.SharePolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SharePolicy) predicate.SharePolicy {
	return predicate.SharePolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SharePolicy) predicate.SharePolicy {
	return predicate.SharePolicy(sql.NotPredicates(p))
}
