// Code generated by ent, DO NOT EDIT.

package accountshareroom

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/your-org/ai-gateway-platform/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldAccountID, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldOwnerUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldName, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldStatus, v))
}

// SeatLimit applies equality check predicate on the "seat_limit" field. It's identical to SeatLimitEQ.
func SeatLimit(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldSeatLimit, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldRateMultiplier, v))
}

// PerUserConcurrency applies equality check predicate on the "per_user_concurrency" field. It's identical to PerUserConcurrencyEQ.
func PerUserConcurrency(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldPerUserConcurrency, v))
}

// QueueMax applies equality check predicate on the "queue_max" field. It's identical to QueueMaxEQ.
func QueueMax(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldQueueMax, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldAccountID, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v int64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldOwnerUserID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldContainsFold(FieldStatus, v))
}

// SeatLimitEQ applies the EQ predicate on the "seat_limit" field.
func SeatLimitEQ(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldSeatLimit, v))
}

// SeatLimitNEQ applies the NEQ predicate on the "seat_limit" field.
func SeatLimitNEQ(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldSeatLimit, v))
}

// SeatLimitIn applies the In predicate on the "seat_limit" field.
func SeatLimitIn(vs ...int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldSeatLimit, vs...))
}

// SeatLimitNotIn applies the NotIn predicate on the "seat_limit" field.
func SeatLimitNotIn(vs ...int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldSeatLimit, vs...))
}

// SeatLimitGT applies the GT predicate on the "seat_limit" field.
func SeatLimitGT(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldSeatLimit, v))
}

// SeatLimitGTE applies the GTE predicate on the "seat_limit" field.
func SeatLimitGTE(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldSeatLimit, v))
}

// SeatLimitLT applies the LT predicate on the "seat_limit" field.
func SeatLimitLT(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldSeatLimit, v))
}

// SeatLimitLTE applies the LTE predicate on the "seat_limit" field.
func SeatLimitLTE(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldSeatLimit, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldRateMultiplier, v))
}

// AllowedModelsIsNil applies the IsNil predicate on the "allowed_models" field.
func AllowedModelsIsNil() predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIsNull(FieldAllowedModels))
}

// AllowedModelsNotNil applies the NotNil predicate on the "allowed_models" field.
func AllowedModelsNotNil() predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotNull(FieldAllowedModels))
}

// PerUserConcurrencyEQ applies the EQ predicate on the "per_user_concurrency" field.
func PerUserConcurrencyEQ(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldPerUserConcurrency, v))
}

// PerUserConcurrencyNEQ applies the NEQ predicate on the "per_user_concurrency" field.
func PerUserConcurrencyNEQ(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldPerUserConcurrency, v))
}

// PerUserConcurrencyIn applies the In predicate on the "per_user_concurrency" field.
func PerUserConcurrencyIn(vs ...int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldPerUserConcurrency, vs...))
}

// PerUserConcurrencyNotIn applies the NotIn predicate on the "per_user_concurrency" field.
func PerUserConcurrencyNotIn(vs ...int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldPerUserConcurrency, vs...))
}

// PerUserConcurrencyGT applies the GT predicate on the "per_user_concurrency" field.
func PerUserConcurrencyGT(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldPerUserConcurrency, v))
}

// PerUserConcurrencyGTE applies the GTE predicate on the "per_user_concurrency" field.
func PerUserConcurrencyGTE(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldPerUserConcurrency, v))
}

// PerUserConcurrencyLT applies the LT predicate on the "per_user_concurrency" field.
func PerUserConcurrencyLT(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldPerUserConcurrency, v))
}

// PerUserConcurrencyLTE applies the LTE predicate on the "per_user_concurrency" field.
func PerUserConcurrencyLTE(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldPerUserConcurrency, v))
}

// QueueMaxEQ applies the EQ predicate on the "queue_max" field.
func QueueMaxEQ(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldQueueMax, v))
}

// QueueMaxNEQ applies the NEQ predicate on the "queue_max" field.
func QueueMaxNEQ(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldQueueMax, v))
}

// QueueMaxIn applies the In predicate on the "queue_max" field.
func QueueMaxIn(vs ...int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldQueueMax, vs...))
}

// QueueMaxNotIn applies the NotIn predicate on the "queue_max" field.
func QueueMaxNotIn(vs ...int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldQueueMax, vs...))
}

// QueueMaxGT applies the GT predicate on the "queue_max" field.
func QueueMaxGT(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldQueueMax, v))
}

// QueueMaxGTE applies the GTE predicate on the "queue_max" field.
func QueueMaxGTE(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldQueueMax, v))
}

// QueueMaxLT applies the LT predicate on the "queue_max" field.
func QueueMaxLT(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldQueueMax, v))
}

// QueueMaxLTE applies the LTE predicate on the "queue_max" field.
func QueueMaxLTE(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldQueueMax, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.FieldLTE(FieldVersion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountShareRoom) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountShareRoom) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountShareRoom) predicate.AccountShareRoom {
	return predicate.AccountShareRoom(sql.NotPredicates(p))
}
